Repository medly/medly-components, pull requests merged in 2021-07, with the labels that each got.

#308 feat(core): introduce XS size in table component
  packages/core/src/components/Table/Body/Cell/ExtendedRowCell/ExtendedRowCell.styled.tsx
  packages/core/src/components/Table/Body/Cell/RowActionsCell/RowActionsCell.styled.tsx
  packages/core/src/components/Table/Body/Cell/RowActionsCell/RowActionsCell.tsx
  packages/core/src/components/Table/Body/Cell/Styled/Cell.styled.tsx
  packages/core/src/components/Table/Foot/Foot.styled.tsx
  packages/core/src/components/Table/Foot/Foot.tsx
  packages/core/src/components/Table/Head/Head.tsx
  packages/core/src/components/Table/Head/HeadCell/HeadCell.styled.tsx
  packages/core/src/components/Table/__snapshots__/Table.test.tsx.snap
  packages/core/src/components/Table/docs/Table.stories.mdx
  packages/core/src/components/Table/helpers.ts
  packages/core/src/components/Table/types.ts
Labels: size/M

#307 feat(core, theme): adds pressed state to checkbox and radio components
  packages/core/src/components/Checkbox/Checkbox.stories.mdx
  packages/core/src/components/Checkbox/Checkbox.styled.tsx
  packages/core/src/components/Checkbox/__snapshots__/checkbox.test.tsx.snap
  packages/core/src/components/CheckboxGroup/__snapshots__/CheckboxGroup.test.tsx.snap
  packages/core/src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  packages/core/src/components/Radio/Radio.styled.tsx
  packages/core/src/components/Radio/__snapshots__/radio.test.tsx.snap
  packages/core/src/components/RadioGroup/__snapshots__/RadioGroup.test.tsx.snap
  packages/core/src/components/Table/Body/Cell/__snapshots__/Cell.test.tsx.snap
  packages/forms/src/components/Form/__snapshots__/Form.test.tsx.snap
  packages/theme/src/core/checkbox/index.ts
  packages/theme/src/core/checkbox/types.ts
  packages/theme/src/core/radio/index.ts
  packages/theme/src/core/radio/types.ts
Labels: size/XXL

#309 fix(core): fix padding of HeadCell button for ‘XS’ tablesize
  packages/core/src/components/Table/Head/HeadCell/HeadCell.styled.tsx
Labels: size/XS

#310 fix(core): updates border-color of selectors when hovered/pressed based on fill-color
  packages/core/src/components/Checkbox/Checkbox.styled.tsx
  packages/core/src/components/Checkbox/__snapshots__/checkbox.test.tsx.snap
  packages/core/src/components/CheckboxGroup/__snapshots__/CheckboxGroup.test.tsx.snap
  packages/core/src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  packages/core/src/components/Table/Body/Cell/__snapshots__/Cell.test.tsx.snap
  packages/forms/src/components/Form/__snapshots__/Form.test.tsx.snap
Labels: size/M

#322 fix(core): fix fitContent table cell width issue for custom cell component
  packages/core/src/components/Table/Body/Cell/Styled/CustomComponentWrapper.styled.tsx
Labels: size/XS

#323 fix: add token while checking out the branch
  .github/workflows/release.yml
Labels: size/XS

#324 feat: add custom hooks to use axios and swr
  jest.config.js
  package.json
  packages/utils/package.json
  packages/utils/src/components/InjectClassName/__snapshots__/InjectClassName.test.tsx.snap
  packages/utils/src/hooks/useAxios/index.ts
  packages/utils/src/hooks/useAxios/types.ts
  packages/utils/src/hooks/useAxios/useAxios.stories.mdx
  packages/utils/src/hooks/useAxios/useAxios.test.tsx
  packages/utils/src/hooks/useAxios/useAxios.ts
  packages/utils/src/hooks/useSWRAxios/index.ts
  packages/utils/src/hooks/useSWRAxios/types.ts
  packages/utils/src/hooks/useSWRAxios/useSWRAxios.stories.mdx
  packages/utils/src/hooks/useSWRAxios/useSWRAxios.test.tsx
  packages/utils/src/hooks/useSWRAxios/useSWRAxios.ts
  packages/utils/src/test-utils.tsx
  yarn.lock
Labels: size/XL

#326 fix: export useAxios and useSWRAxios from utils package
  packages/utils/src/hooks/index.ts
Labels: size/XS

#327 fix(core): fix grouped content cell right border issue
  packages/core/src/components/Table/GroupCell/GroupCell.styled.tsx
  packages/core/src/components/Table/GroupCell/GroupCell.test.tsx
  packages/core/src/components/Table/GroupCell/__snapshots__/GroupCell.test.tsx.snap
  packages/core/src/components/Table/GroupCell/types.ts
  packages/core/src/components/Table/Head/Head.tsx
  packages/core/src/components/Table/__snapshots__/Table.test.tsx.snap
Labels: size/L

#325 feat: single search component updates. PES-1572
  packages/core/src/components/SearchBox/SearchBox.stories.mdx
  packages/core/src/components/SearchBox/SearchBox.styled.tsx
  packages/core/src/components/SearchBox/SearchBox.test.tsx
  packages/core/src/components/SearchBox/SearchBox.tsx
  packages/core/src/components/SearchBox/__snapshots__/SearchBox.test.tsx.snap
  packages/core/src/components/SearchBox/styles/icons.tsx
  packages/core/src/components/SearchBox/styles/options.tsx
  packages/core/src/components/SearchBox/types.ts
  packages/icons/src/assets/Action/caret_double_down.svg
  packages/icons/src/icons/Action/ExpandIcon.tsx
  packages/icons/src/index.ts
  packages/layout/src/components/SideNav/NavItem/__snapshots__/NavItem.test.tsx.snap
  packages/layout/src/components/SideNav/ToggleSwitch/__snapshots__/ToggleSwitch.test.tsx.snap
  packages/layout/src/components/SideNav/__snapshots__/SideNav.test.tsx.snap
  packages/theme/src/core/searchBox/index.ts
  packages/theme/src/core/searchBox/types.ts
Labels: size/L

#329 fix(core): fix build error
  yarn.lock
Labels: size/XS

#330 docs: improve popover storybook previews
  packages/core/src/components/DatePicker/__snapshots__/DatePicker.test.tsx.snap
  packages/core/src/components/DateRangePicker/__snapshots__/DateRangePicker.test.tsx.snap
  packages/core/src/components/Popover/Popover.stories.mdx
  packages/core/src/components/Popover/Popover.stories.tsx
Labels: size/L
