Repository medly/medly-components, pull requests merged in 2021-03, with the labels that each got.

#261 fix(core): fix minimap positioning issue when no results are present in table
  packages/core/src/components/Table/Body/Body.tsx
  packages/core/src/components/Table/Body/Row/Row.styled.tsx
  packages/core/src/components/Table/Body/Row/Row.test.tsx
  packages/core/src/components/Table/Body/Row/__snapshots__/Row.test.tsx.snap
Labels: size/M

#256 docs(core/toggle): Updated toggle component's documentation
  packages/core/src/components/Toggle/Toggle.stories.mdx
  packages/core/src/components/Toggle/Toggle.stories.tsx
Labels: size/M

#264 fix: navigator undefined issue
  packages/utils/src/helpers/isMobile.ts
Labels: size/XS

#265 PNA-466: Mobile DatePicker
  packages/forms/src/hooks/useForm/useForm.ts
Labels: size/XS

#267 fix(core): fix null being treated as custom component
  packages/core/src/components/SingleSelect/Options/Option/Option.tsx
  packages/core/src/components/SingleSelect/SingleSelect.test.tsx
Labels: size/S

#270 fix(core): fix minimap positioning issue on table column resize, table resize
  packages/core/src/components/Table/Minimap/Minimap.styled.tsx
  packages/core/src/components/Table/Minimap/Minimap.tsx
  packages/core/src/components/Table/Minimap/__snapshots__/Minimap.test.tsx.snap
Labels: size/M

#271 fix(core): fix minimap resize and controller positioning issue on table resize
  packages/core/package.json
  packages/core/src/components/Table/Minimap/Minimap.tsx
Labels: size/M

#273 fix(core): textField - setIsTextPresent updates based on value not on onChange of field
  packages/core/src/components/TextField/TextField.tsx
Labels: size/XS

#272 fix(core): fix table footer style to keep it visible on table vertical scroll
  packages/core/src/components/Table/Foot/Foot.styled.tsx
  packages/core/src/components/Table/__snapshots__/Table.test.tsx.snap
Labels: size/XS

#274 feat: update the type of fieldSchema in Form component to object and …
  packages/forms/src/components/Form/Form.stories.mdx
  packages/forms/src/components/Form/Form.test.tsx
  packages/forms/src/components/Form/Form.tsx
  packages/forms/src/components/Form/types.ts
Labels: size/M

#275 fix: remove isMobile functionality
  packages/core/src/components/DatePicker/DatePicker.stories.mdx
  packages/core/src/components/DatePicker/DatePicker.tsx
  packages/forms/src/hooks/useForm/useForm.ts
  packages/utils/src/helpers/index.ts
  packages/utils/src/helpers/isMobile.ts
Labels: size/M
