Repository medly/medly-components, pull requests merged in 2021-09, with the labels that each got.

#403 feat(forms): allow adding custom fields to forms
  packages/forms/src/components/Fields/Fields.components.tsx
  packages/forms/src/components/Fields/types.ts
  packages/forms/src/components/Form/Form.stories.tsx
  packages/forms/src/components/Form/Form.test.tsx
  packages/forms/src/components/Form/stories/AddPhoneNumber.tsx
  packages/forms/src/components/Form/stories/AdvancedForm.stories.mdx
  packages/forms/src/components/Form/stories/CustomPhoneField.tsx
  packages/forms/src/components/Form/stories/Form.stories.mdx
  packages/forms/src/components/Form/stories/Form.stories.tsx
  packages/forms/src/hooks/useForm/types.ts
  packages/forms/src/hooks/useForm/useForm.ts
Labels: size/L

#407 fix: singleSelect component error message issue
  jest.config.js
  packages/core/src/components/SingleSelect/SingleSelect.tsx
Labels: size/S

#401 feat: add storage utilities
  packages/utils/src/helpers/cookieStorage/cookieStorage.test.ts
  packages/utils/src/helpers/cookieStorage/cookieStorage.ts
  packages/utils/src/helpers/cookieStorage/index.ts
  packages/utils/src/helpers/cookieStorage/localStorage.stories.mdx
  packages/utils/src/helpers/index.ts
  packages/utils/src/helpers/localStorage/index.ts
  packages/utils/src/helpers/localStorage/localStorage.stories.mdx
  packages/utils/src/helpers/localStorage/localStorage.test.ts
  packages/utils/src/helpers/localStorage/localStorage.ts
  packages/utils/src/helpers/sessionStorage/index.ts
  packages/utils/src/helpers/sessionStorage/sessionStorage.stories.mdx
  packages/utils/src/helpers/sessionStorage/sessionStorage.test.ts
  packages/utils/src/helpers/sessionStorage/sessionStorage.ts
  packages/utils/src/helpers/storage/index.ts
  packages/utils/src/helpers/storage/storage.ts
  packages/utils/src/helpers/storage/types.ts
  packages/utils/src/hooks/index.ts
  packages/utils/src/hooks/useStorage/Storage.context.tsx
  packages/utils/src/hooks/useStorage/index.ts
  packages/utils/src/hooks/useStorage/types.ts
  packages/utils/src/hooks/useStorage/useStorage.stories.mdx
  packages/utils/src/hooks/useStorage/useStorage.test.tsx
  packages/utils/src/hooks/useStorage/useStorage.ts
Labels: size/L

#406 More updates to searchBox component
  packages/core/src/components/SearchBox/SearchBox.styled.tsx
  packages/core/src/components/SearchBox/SearchBox.tsx
  packages/core/src/components/SearchBox/__snapshots__/SearchBox.test.tsx.snap
  packages/core/src/components/SearchBox/styles/icons.tsx
  packages/core/src/components/SearchBox/styles/utils.tsx
  packages/icons/src/assets/Action/search_24px_rounded.svg
  packages/layout/src/components/SideNav/__snapshots__/SideNav.test.tsx.snap
Labels: size/L

#408 fix: pass all the props of modal content to the styled component
  packages/core/src/components/Modal/Content/Content.tsx
Labels: size/XS

#409 fix: wrong error validation in datepicker component
  packages/core/src/components/DatePicker/DatePicker.test.tsx
  packages/core/src/components/DatePicker/DatePicker.tsx
  packages/forms/src/components/Form/__snapshots__/Form.test.tsx.snap
  packages/forms/src/components/Form/testSchema.ts
Labels: size/XL

#410 fix: window object undefined in local and session storage
  packages/utils/src/helpers/localStorage/localStorage.ts
  packages/utils/src/helpers/sessionStorage/sessionStorage.ts
  packages/utils/src/hooks/useStorage/useStorage.ts
Labels: size/S

#414 fix: context undefined issue in header nav component in cjs
  packages/layout/src/components/Header/Nav/Nav.tsx
Labels: size/XS

#415 feat: add font display in font face
  packages/core/src/components/CssBaseline/fonts.tsx
  packages/theme/src/core/font/faces.ts
  packages/theme/src/core/font/types.ts
Labels: size/S

#416 feat: adding border radius for table header cell into theme
  packages/core/src/components/Table/Head/HeadCell/HeadCell.styled.tsx
  packages/theme/src/core/table/index.ts
  packages/theme/src/core/table/types.ts
Labels: size/XS

#413 fix searchBox component
  packages/core/src/components/SearchBox/__snapshots__/SearchBox.test.tsx.snap
  packages/core/src/components/SearchBox/styles/icons.tsx
Labels: size/M

#419 fix: types of custom component in forms package
  packages/forms/src/components/Fields/types.ts
  packages/forms/src/components/Form/Form.test.tsx
  packages/forms/src/components/Form/stories/AddPhoneNumber.tsx
  packages/forms/src/components/Form/stories/AdvancedForm.stories.mdx
  packages/forms/src/components/Form/stories/CustomPhoneField.tsx
  packages/forms/src/components/Form/stories/Form.stories.tsx
  packages/forms/src/components/Form/types.ts
  packages/forms/src/components/index.ts
Labels: size/M

#418 Feat/add color type
  docs/Colors/Colors.stories.tsx
  packages/theme/src/core/colors/types.ts
Labels: size/S

#421 feat(core): add and use new single-select props for suffix icon + hovered color
  packages/core/src/components/DateRangePicker/__snapshots__/DateRangePicker.test.tsx.snap
  packages/core/src/components/SearchBox/__snapshots__/SearchBox.test.tsx.snap
  packages/core/src/components/SingleSelect/Options/Option/Option.styled.tsx
  packages/core/src/components/SingleSelect/SingleSelect.stories.mdx
  packages/core/src/components/SingleSelect/SingleSelect.tsx
  packages/core/src/components/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap
  packages/core/src/components/SingleSelect/types.ts
  packages/theme/src/core/singleSelect/index.ts
  packages/theme/src/core/singleSelect/types.ts
Labels: size/L

#422 feat(theme): allow adding border to modal close icon
  packages/core/src/components/Modal/CloseIcon/CloseIcon.styled.tsx
  packages/core/src/components/Modal/__snapshots__/Modal.test.tsx.snap
  packages/theme/src/core/modal/index.ts
  packages/theme/src/core/modal/types.ts
Labels: size/XS

#411 PSB | fix: window object undefined issue in nextJs
  packages/layout/src/components/SideNav/SideNav.tsx
  packages/utils/src/hooks/useMediaQuery/useMediaQuery.ts
  packages/utils/src/hooks/useWindowSize.ts
Labels: size/XS

#426 docs: adds props naming rules to `contributing.md` file
  CONTRIBUTING.md
Labels: size/S

#424 feat(core): textfield custom active border styles
  packages/core/src/components/DatePicker/__snapshots__/DatePicker.test.tsx.snap
  packages/core/src/components/DateRangePicker/__snapshots__/DateRangePicker.test.tsx.snap
  packages/core/src/components/HelperAndErrorTextTooltip/HelperAndErrorTextTooltip.styled.tsx
  packages/core/src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  packages/core/src/components/SingleSelect/SingleSelect.stories.mdx
  packages/core/src/components/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap
  packages/core/src/components/TextField/Styled/HelperAndErrorTextTooltipWrapper.styled.tsx
  packages/core/src/components/TextField/Styled/InnerWrapper/InnerWrapper.styled.tsx
  packages/core/src/components/TextField/Styled/InnerWrapper/fusion.styled.tsx
  packages/core/src/components/TextField/Styled/InnerWrapper/outlined.styled.tsx
  packages/core/src/components/TextField/Styled/TextField.styled.tsx
  packages/core/src/components/TextField/TextField.stories.mdx
  packages/core/src/components/TextField/TextField.test.tsx
  packages/core/src/components/TextField/TextField.tsx
  packages/core/src/components/TextField/__snapshots__/TextField.test.tsx.snap
  packages/forms/src/components/Form/__snapshots__/Form.test.tsx.snap
  packages/theme/src/core/textField/index.ts
  packages/theme/src/core/textField/types.ts
Labels: size/XXL

#427 fix: validation meesage issue in DateRangePicker component
  packages/core/src/components/CssBaseline/CssBaseline.styled.tsx
  packages/core/src/components/DateRangePicker/DateRangePicker.test.tsx
  packages/core/src/components/DateRangePicker/DateRangePicker.tsx
  packages/core/src/components/DateRangePicker/DateRangeTextFields/DateRangeTextFields.tsx
  packages/core/src/components/DateRangePicker/DateRangeTextFields/types.ts
  packages/core/src/components/DateRangePicker/DateRangeTextFields/useDateRangeTextFieldsHandlers.ts
  packages/core/src/components/DateRangePicker/__snapshots__/DateRangePicker.test.tsx.snap
Labels: size/M

#428 fix: empty string as initialValue in useStorage
  packages/utils/src/hooks/useStorage/useStorage.ts
Labels: size/XS

#429 fix: update state issue when component is unmounted
  packages/utils/src/hooks/useStorage/useStorage.ts
Labels: size/S

#430 feat: add onInputChange prop in MultiSelect component
  packages/core/src/components/MultiSelect/MultiSelect.test.tsx
  packages/core/src/components/MultiSelect/MultiSelect.tsx
  packages/core/src/components/MultiSelect/types.ts
Labels: size/S

#423 Center aligning table header text
  packages/core/src/components/Table/Head/HeadCell/HeadCell.styled.tsx
  packages/core/src/components/Table/__snapshots__/Table.test.tsx.snap
Labels: size/S

#431 refactor: fix strict null check ts issues in icons, loaders, layout, …
  packages/icons/src/SvgIcon/SvgIcon.styled.tsx
  packages/layout/src/components/Header/Header.context.tsx
  packages/layout/src/components/Header/Header.test.tsx
  packages/layout/src/components/SideNav/NavItem/NavItem.test.tsx
  packages/layout/src/components/SideNav/SideNav.context.tsx
  packages/layout/src/components/SideNav/SideNav.test.tsx
  packages/layout/src/components/SideNav/ToggleSwitch/ToggleSwitch.tsx
  packages/layout/src/components/SideNav/ToggleSwitch/__snapshots__/ToggleSwitch.test.tsx.snap
  packages/layout/src/components/SideNav/__snapshots__/SideNav.test.tsx.snap
  packages/loaders/src/SvgLoader/SvgLoader.styled.tsx
  packages/theme/src/core/colors/medlyGreen.ts
  packages/theme/src/core/colors/types.ts
  packages/theme/src/types.ts
  packages/utils/src/helpers/debounce.ts
  packages/utils/src/hooks/useAxios/types.ts
  packages/utils/src/hooks/useSWRAxios/types.ts
  packages/utils/src/hooks/useSWRAxios/useSWRAxios.test.tsx
  packages/utils/src/hooks/useStorage/useStorage.ts
  packages/utils/src/styled.ts
Labels: size/L

#425 feat: checkbox + radio selectors style updates
  packages/core/src/components/Checkbox/Checkbox.tsx
  packages/core/src/components/Radio/Radio.tsx
  packages/core/src/components/Selectors/Selectors.styled.tsx
  packages/theme/src/core/checkbox/index.ts
  packages/theme/src/core/checkbox/types.ts
  packages/theme/src/core/radio/index.ts
  packages/theme/src/core/radio/types.ts
Labels: size/M

#433 fix: style issue of text component used in table rows
  packages/core/src/components/Table/Body/Cell/Cell.tsx
  packages/core/src/components/Table/Body/Row/Row.styled.tsx
  packages/core/src/components/Table/Body/Row/__snapshots__/Row.test.tsx.snap
  packages/core/src/components/Table/Table.test.tsx
  packages/core/src/components/Table/__snapshots__/Table.test.tsx.snap
Labels: size/XXL

#434 feat: adds `removeAllToasts` method to clear all toasts from DOM
  packages/core/src/components/ToastContainer/ToastContainer.stories.mdx
  packages/core/src/components/ToastContainer/ToastContainer.test.tsx
  packages/core/src/components/ToastContainer/ToastStore.ts
  packages/core/src/components/ToastContainer/__snapshots__/ToastContainer.test.tsx.snap
  packages/core/src/components/index.ts
Labels: size/M

#436 fix: strict null check in loaders package
  packages/loaders/src/loaders/CircleLoader.tsx
  packages/loaders/src/loaders/ConcentricCircleLoader.tsx
  packages/loaders/src/loaders/DotsBouncingLoader.tsx
  packages/loaders/src/loaders/DotsLoader.tsx
Labels: size/S

#435 fix: strict null check in forms package
  packages/forms/src/components/Actions/Actions.tsx
  packages/forms/src/components/Actions/types.ts
  packages/forms/src/components/Fields/Fields.components.tsx
  packages/forms/src/components/Form/Form.test.tsx
  packages/forms/src/components/Form/Form.tsx
  packages/forms/src/components/Form/__snapshots__/Form.test.tsx.snap
  packages/forms/src/components/Form/types.ts
  packages/forms/src/hooks/useForm/types.ts
  packages/forms/src/hooks/useForm/useForm.ts
  packages/layout/src/components/SideNav/NavItem/NavItem.tsx
Labels: size/XL

#439 fix: strict null check issue in Toggle, ToastContainer, Toast, TextFi…
  packages/core/src/components/Button/types.ts
  packages/core/src/components/DateRangePicker/DateRangeTextFields/DateRangeTextField/DateRangeTextField.tsx
  packages/core/src/components/DateRangePicker/DateRangeTextFields/DateRangeTextField/types.ts
  packages/core/src/components/FieldWithLabel/FieldWithLabel.styled.tsx
  packages/core/src/components/FieldWithLabel/types.ts
  packages/core/src/components/HelperAndErrorTextTooltip/HelperAndErrorTextTooltip.tsx
  packages/core/src/components/Selectors/Selectors.styled.tsx
  packages/core/src/components/Tabs/Tab/Tab.styled.tsx
  packages/core/src/components/Tabs/Tab/Tab.test.tsx
  packages/core/src/components/Tabs/Tab/types.ts
  packages/core/src/components/Tabs/TabList/TabList.styled.tsx
  packages/core/src/components/Tabs/TabList/TabList.tsx
  packages/core/src/components/Tabs/TabList/__snapshots__/TabList.test.tsx.snap
  packages/core/src/components/Tabs/TabList/types.ts
  packages/core/src/components/Tabs/Tabs.context.tsx
  packages/core/src/components/Tabs/Tabs.test.tsx
  packages/core/src/components/Tabs/Tabs.tsx
  packages/core/src/components/Text/Text.styled.tsx
  packages/core/src/components/Text/types.ts
  packages/core/src/components/TextField/Styled/CharacterCount.styled.tsx
  packages/core/src/components/TextField/Styled/InnerWrapper/InnerWrapper.styled.tsx
  packages/core/src/components/TextField/Styled/InnerWrapper/filled.styled.tsx
  packages/core/src/components/TextField/Styled/InnerWrapper/fusion.styled.tsx
  packages/core/src/components/TextField/Styled/InnerWrapper/outlined.styled.tsx
  packages/core/src/components/TextField/Styled/Label.styled.tsx
  packages/core/src/components/TextField/Styled/OuterWrapper.styled.tsx
  packages/core/src/components/TextField/Styled/TextField.styled.tsx
  packages/core/src/components/TextField/TextField.stories.tsx
  packages/core/src/components/TextField/TextField.test.tsx
  packages/core/src/components/TextField/TextField.tsx
  packages/core/src/components/TextField/types.ts
  packages/core/src/components/Toast/Toast.stories.mdx
  packages/core/src/components/Toast/Toast.styled.tsx
  packages/core/src/components/Toast/Toast.test.tsx
  packages/core/src/components/Toast/types.ts
  packages/core/src/components/ToastContainer/ToastContainer.component.tsx
  packages/core/src/components/ToastContainer/ToastContainer.test.tsx
  packages/core/src/components/ToastContainer/ToastStore.ts
  packages/core/src/components/Toggle/Toggle.styled.tsx
  packages/core/src/components/Toggle/Toggle.test.tsx
  packages/core/src/components/Toggle/types.ts
  packages/core/src/types.ts
  packages/icons/src/SvgIcon/SvgIcon.styled.tsx
  packages/icons/src/SvgIcon/types.ts
  packages/loaders/src/SvgLoader/SvgLoader.styled.tsx
  packages/loaders/src/SvgLoader/types.ts
  packages/utils/src/hooks/useCombinedRefs.ts
  packages/utils/src/types/HTMLProps.ts
Labels: size/XL

#455 docs: made changes to readme, contributing, and Code of conduct.
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: size/M

#457 fix: css prop issue in toast component
  packages/core/src/components/Toast/Toast.tsx
  packages/core/src/components/Toast/types.ts
Labels: size/S

#453 fix: strict null check issue in table component
  packages/core/src/components/Table/ActionBar/ActionBar.tsx
  packages/core/src/components/Table/Body/Body.tsx
  packages/core/src/components/Table/Body/Cell/Cell.test.tsx
  packages/core/src/components/Table/Body/Cell/Cell.tsx
  packages/core/src/components/Table/Body/Cell/ExtendedRowCell/ExtendedRowCell.styled.tsx
  packages/core/src/components/Table/Body/Cell/ExtendedRowCell/ExtendedRowCell.tsx
  packages/core/src/components/Table/Body/Cell/ExtendedRowCell/types.ts
  packages/core/src/components/Table/Body/Cell/RowActionsCell/RowActionsCell.tsx
  packages/core/src/components/Table/Body/Cell/RowHoverActionsCell/RowHoverActionsCell.tsx
  packages/core/src/components/Table/Body/Cell/Styled/Cell.styled.tsx
  packages/core/src/components/Table/Body/Cell/__snapshots__/Cell.test.tsx.snap
  packages/core/src/components/Table/Body/Cell/types.ts
  packages/core/src/components/Table/Body/GroupedRow/GroupedRow.tsx
  packages/core/src/components/Table/Body/GroupedRow/TitleRow/TitleRow.styled.tsx
  packages/core/src/components/Table/Body/GroupedRow/TitleRow/TitleRow.tsx
  packages/core/src/components/Table/Body/GroupedRow/TitleRow/types.ts
  packages/core/src/components/Table/Body/Row/Row.tsx
  packages/core/src/components/Table/Body/Row/types.ts
  packages/core/src/components/Table/Body/types.ts
  packages/core/src/components/Table/ColumnConfiguration/helpers.ts
  packages/core/src/components/Table/Foot/Foot.styled.tsx
  packages/core/src/components/Table/Foot/Foot.tsx
  packages/core/src/components/Table/Foot/types.ts
  packages/core/src/components/Table/GroupCell/types.ts
  packages/core/src/components/Table/Head/Head.tsx
  packages/core/src/components/Table/Head/HeadCell/HeadCell.styled.tsx
  packages/core/src/components/Table/Head/HeadCell/HeadCell.tsx
  packages/core/src/components/Table/Head/HeadCell/types.ts
  packages/core/src/components/Table/Minimap/Minimap.test.tsx
  packages/core/src/components/Table/Minimap/Minimap.tsx
  packages/core/src/components/Table/Table.tsx
  packages/core/src/components/Table/context/TableComponentsCommonProps.context.tsx
  packages/core/src/components/Table/context/TableState.context.tsx
  packages/core/src/components/Table/docs/Table.stories.tsx
  packages/core/src/components/Table/helpers.ts
  packages/core/src/components/Table/useGroupedRowSelector.ts
  packages/core/src/components/Table/useRowSelector.ts
  packages/theme/src/core/pagination/types.ts
  packages/theme/src/core/table/types.ts
Labels: size/L

#454 fix: strict null check issue in stepper component
  packages/core/src/components/Stepper/Stepper.stories.tsx
  packages/core/src/components/Stepper/types.ts
Labels: size/XS

#461 fix: strict null check for Radio and RadioGroup component
  packages/core/src/components/Radio/Radio.stories.tsx
  packages/core/src/components/Radio/Radio.styled.tsx
  packages/core/src/components/Radio/Radio.tsx
  packages/core/src/components/Radio/radio.test.tsx
  packages/core/src/components/Radio/types.ts
  packages/core/src/components/RadioGroup/RadioGroup.stories.tsx
  packages/core/src/components/RadioGroup/RadioGroup.test.tsx
  packages/core/src/components/RadioGroup/RadioGroup.tsx
  packages/core/src/components/RadioGroup/types.ts
Labels: size/M

#460 fix: strict null check issue in searchbox component
  packages/core/src/components/SearchBox/SearchBox.styled.tsx
  packages/core/src/components/SearchBox/SearchBox.test.tsx
  packages/core/src/components/SearchBox/SearchBox.tsx
  packages/core/src/components/SearchBox/__snapshots__/SearchBox.test.tsx.snap
  packages/core/src/components/SearchBox/styles/icons.tsx
  packages/core/src/components/SearchBox/styles/options.tsx
  packages/core/src/components/SearchBox/styles/utils.tsx
  packages/core/src/components/SearchBox/types.ts
Labels: size/L

#465 fix: fix regex Denial of service and Weak Cryptography issue
  jest.setupAfterEnv.js
  package.json
  packages/core/src/components/Avatar/Avatar.test.tsx
  packages/core/src/components/Avatar/__snapshots__/Avatar.test.tsx.snap
  packages/core/src/components/Table/helpers.ts
  packages/core/src/components/TextField/getMaskedValue.ts
  packages/core/src/components/ToastContainer/ToastStore.ts
  yarn.lock
Labels: size/M

#459 Fix table header cells that don't contain icons
  packages/core/src/components/Table/Head/HeadCell/HeadCell.styled.tsx
  packages/core/src/components/Table/__snapshots__/Table.test.tsx.snap
Labels: size/S

#464 fix: fix strict null check issue in Popup & Pagination component
  packages/core/src/components/Pagination/Pagination.test.tsx
  packages/core/src/components/Pagination/Pagination.tsx
  packages/core/src/components/Pagination/PaginationPopup/PaginationPopup.test.tsx
  packages/core/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
  packages/core/src/components/Popover/Popover.test.tsx
  packages/core/src/components/Popover/Popover.tsx
  packages/core/src/components/Popover/Popup/Popup.test.tsx
  packages/core/src/components/Popover/Popup/Popup.tsx
  packages/core/src/components/Popover/Popup/styled/Popup.styled.tsx
  packages/core/src/components/Popover/Popup/types.ts
  packages/core/src/components/Popover/types.ts
  packages/core/src/components/Table/__snapshots__/Table.test.tsx.snap
Labels: size/L
