Repository medly/medly-components, pull requests merged in 2021-08, with the labels that each got.

#334 fix: change the key of swr from request object to url
  packages/utils/src/hooks/useSWRAxios/types.ts
  packages/utils/src/hooks/useSWRAxios/useSWRAxios.stories.mdx
  packages/utils/src/hooks/useSWRAxios/useSWRAxios.ts
Labels: size/S

#335 fix: trigger release workflow on push instead of pull_request merge
  .github/workflows/release.yml
  lerna.json
Labels: size/XS

#333 refactor(core): remove withActionBar prop from table component
  packages/core/src/components/Table/Table.tsx
  packages/core/src/components/Table/docs/Table.stories.mdx
  packages/core/src/components/Table/types.ts
Labels: size/S

#320 feat: add "solid" tabs variant
  packages/core/src/components/Tabs/Tab/Tab.styled.tsx
  packages/core/src/components/Tabs/Tab/Tab.test.tsx
  packages/core/src/components/Tabs/Tab/Tab.tsx
  packages/core/src/components/Tabs/Tab/__snapshots__/Tab.test.tsx.snap
  packages/core/src/components/Tabs/Tab/types.ts
  packages/core/src/components/Tabs/TabList/TabList.styled.tsx
  packages/core/src/components/Tabs/TabList/TabList.tsx
  packages/core/src/components/Tabs/TabList/__snapshots__/TabList.test.tsx.snap
  packages/core/src/components/Tabs/TabList/types.ts
  packages/core/src/components/Tabs/Tabs.context.tsx
  packages/core/src/components/Tabs/Tabs.stories.mdx
  packages/core/src/components/Tabs/Tabs.stories.tsx
  packages/core/src/components/Tabs/Tabs.test.tsx
  packages/core/src/components/Tabs/Tabs.tsx
  packages/core/src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
  packages/core/src/components/Tabs/types.ts
  packages/layout/src/components/SideNav/NavItem/__snapshots__/NavItem.test.tsx.snap
  packages/layout/src/components/SideNav/ToggleSwitch/__snapshots__/ToggleSwitch.test.tsx.snap
  packages/layout/src/components/SideNav/__snapshots__/SideNav.test.tsx.snap
  packages/theme/src/core/tabs/index.ts
  packages/theme/src/core/tabs/types.ts
Labels: size/XXL

#336 feat: add `isLoading` prop to form component
  packages/core/src/components/Button/Button.stories.tsx
  packages/core/src/components/Button/Button.styled.tsx
  packages/core/src/components/Button/Button.test.tsx
  packages/core/src/components/Button/Button.tsx
  packages/core/src/components/Button/Loader/types.ts
  packages/core/src/components/Button/styles/flatButton.tsx
  packages/core/src/components/Button/styles/outlinedButton.tsx
  packages/core/src/components/Button/styles/solidButton.tsx
  packages/core/src/components/Button/types.ts
  packages/core/src/components/Toast/types.ts
  packages/forms/src/components/Actions/Actions.tsx
  packages/forms/src/components/Actions/types.ts
  packages/forms/src/components/Fields/Fields.components.tsx
  packages/forms/src/components/Fields/types.ts
  packages/forms/src/components/Form/Form.stories.mdx
  packages/forms/src/components/Form/Form.tsx
  packages/forms/src/components/Form/types.ts
Labels: size/L

#338 refactor: change avatar prop name to AvatarProps
  packages/core/src/components/Avatar/Avatar.stories.tsx
  packages/core/src/components/Avatar/Avatar.tsx
  packages/core/src/components/Avatar/types.ts
Labels: size/S

#339 refactor: change card prop name to CardProps
  packages/core/src/components/Card/Card.stories.tsx
  packages/core/src/components/Card/Card.styled.tsx
  packages/core/src/components/Card/Card.test.tsx
  packages/core/src/components/Card/Card.tsx
  packages/core/src/components/Card/types.ts
Labels: size/M

#341 refactor: change checkbox prop name to CheckboxProps
  packages/core/src/components/Checkbox/Checkbox.stories.tsx
  packages/core/src/components/Checkbox/Checkbox.styled.tsx
  packages/core/src/components/Checkbox/Checkbox.tsx
  packages/core/src/components/Checkbox/types.ts
Labels: size/S

#342 refactor: change checkboxgroup prop name to CheckboxGroupProps
  packages/core/src/components/CheckboxGroup/CheckboxGroup.stories.tsx
  packages/core/src/components/CheckboxGroup/CheckboxGroup.tsx
  packages/core/src/components/CheckboxGroup/getValuesFromOptions.ts
  packages/core/src/components/CheckboxGroup/types.ts
Labels: size/S

#340 refactor: change cardtable prop name to CardTableProps
  packages/core/src/components/CardTable/CardTable.tsx
  packages/core/src/components/CardTable/types.ts
Labels: size/XS

#343 refactor: change chip prop name to ChipProps
  packages/core/src/components/Chip/Chip.stories.tsx
  packages/core/src/components/Chip/Chip.tsx
  packages/core/src/components/Chip/types.ts
Labels: size/S

#344 refactor: change dialogbox prop name to DialogBoxProps
  packages/core/src/components/DialogBox/DialogBox.test.tsx
  packages/core/src/components/DialogBox/DialogBox.tsx
  packages/core/src/components/DialogBox/Header/Header.styled.tsx
  packages/core/src/components/DialogBox/Header/types.ts
  packages/core/src/components/DialogBox/Popup/Popup.styled.tsx
  packages/core/src/components/DialogBox/Popup/Popup.test.tsx
  packages/core/src/components/DialogBox/Popup/Popup.tsx
  packages/core/src/components/DialogBox/Popup/types.ts
  packages/core/src/components/DialogBox/types.ts
Labels: size/M

#347 refactor: change fileinput prop name to FileInputProps
  packages/core/src/components/FileInput/FileInput.stories.tsx
  packages/core/src/components/FileInput/FileInput.tsx
  packages/core/src/components/FileInput/types.ts
Labels: size/S

#345 refactor: change drawer prop name to DrawerProps
  packages/core/src/components/Drawer/Drawer.tsx
  packages/core/src/components/Drawer/Footer/Footer.styled.tsx
  packages/core/src/components/Drawer/Footer/Footer.tsx
  packages/core/src/components/Drawer/Footer/types.ts
  packages/core/src/components/Drawer/types.ts
Labels: size/S

#346 refactor: change fieldwithlabel prop name to FieldWithLabelProps
  packages/core/src/components/FieldWithLabel/FieldWithLabel.tsx
  packages/core/src/components/FieldWithLabel/types.ts
Labels: size/XS

#354 refactor: change pagination popup prop name to PaginationPopupProps
  packages/core/src/components/Pagination/PaginationPopup/PaginationPopup.tsx
  packages/core/src/components/Pagination/PaginationPopup/types.ts
Labels: size/XS

#355 refactor: change popover prop name to PopoverProps
  packages/core/src/components/Popover/Popover.styled.tsx
  packages/core/src/components/Popover/Popover.tsx
  packages/core/src/components/Popover/Popup/Popup.test.tsx
  packages/core/src/components/Popover/Popup/Popup.tsx
  packages/core/src/components/Popover/Popup/styled/Popup.styled.tsx
  packages/core/src/components/Popover/Popup/styled/WithArrow.tsx
  packages/core/src/components/Popover/Popup/types.ts
  packages/core/src/components/Popover/types.ts
Labels: size/M

#349 refactor: change input prop name to InputProps
  packages/core/src/components/Input/Input.stories.tsx
  packages/core/src/components/Input/Input.styled.tsx
  packages/core/src/components/Input/Input.tsx
  packages/core/src/components/Input/types.ts
Labels: size/S

#352 refactor: change list prop name to ListProps
  packages/core/src/components/List/List.stories.tsx
  packages/core/src/components/List/List.styled.tsx
  packages/core/src/components/List/List.tsx
  packages/core/src/components/List/types.ts
Labels: size/S

#351 refactor: change link prop name to LinkProps
  packages/core/src/components/Link/Link.tsx
  packages/core/src/components/Link/types.ts
Labels: size/XS

#356 refactor: change radio prop name to RadioProps
  packages/core/src/components/Radio/Radio.stories.tsx
  packages/core/src/components/Radio/Radio.styled.tsx
  packages/core/src/components/Radio/Radio.tsx
  packages/core/src/components/Radio/types.ts
Labels: size/S

#357 refactor: change radiogroup prop name to RadioGroupProps
  packages/core/src/components/RadioGroup/RadioGroup.stories.tsx
  packages/core/src/components/RadioGroup/RadioGroup.tsx
  packages/core/src/components/RadioGroup/types.ts
Labels: size/S

#359 refactor: change stepper prop name to StepperProps
  packages/core/src/components/Stepper/Stepper.stories.tsx
  packages/core/src/components/Stepper/Stepper.test.tsx
  packages/core/src/components/Stepper/Stepper.tsx
  packages/core/src/components/Stepper/types.ts
Labels: size/S

#358 refactor: change searchbox prop name to SearchBoxProps
  packages/core/src/components/SearchBox/SearchBox.stories.tsx
  packages/core/src/components/SearchBox/SearchBox.styled.tsx
  packages/core/src/components/SearchBox/SearchBox.test.tsx
  packages/core/src/components/SearchBox/SearchBox.tsx
  packages/core/src/components/SearchBox/styles/icons.tsx
  packages/core/src/components/SearchBox/styles/options.tsx
  packages/core/src/components/SearchBox/styles/utils.tsx
  packages/core/src/components/SearchBox/types.ts
Labels: size/M

#363 refactor: change toastcontainer prop name to ToastContainerProps
  packages/core/src/components/ToastContainer/ToastContainer.component.tsx
  packages/core/src/components/ToastContainer/ToastContainer.stories.tsx
  packages/core/src/components/ToastContainer/ToastContainer.styled.tsx
  packages/core/src/components/ToastContainer/ToastContainer.test.tsx
  packages/core/src/components/ToastContainer/types.ts
Labels: size/S

#362 refactor: change text prop name to Textprops
  packages/core/src/components/Text/Text.styled.tsx
  packages/core/src/components/Text/Text.tsx
  packages/core/src/components/Text/types.ts
Labels: size/S

#361 refactor: change tabs prop name
  packages/core/src/components/Tabs/Tab/Tab.test.tsx
  packages/core/src/components/Tabs/Tab/Tab.tsx
  packages/core/src/components/Tabs/Tab/types.ts
  packages/core/src/components/Tabs/TabList/TabList.tsx
  packages/core/src/components/Tabs/TabList/types.ts
  packages/core/src/components/Tabs/TabPanel/TabPanel.tsx
  packages/core/src/components/Tabs/TabPanel/types.ts
  packages/core/src/components/Tabs/Tabs.test.tsx
  packages/core/src/components/Tabs/Tabs.tsx
  packages/core/src/components/Tabs/types.ts
Labels: size/M

#364 refactor: change toggle prop name to ToggleProps
  packages/core/src/components/Toggle/Toggle.stories.tsx
  packages/core/src/components/Toggle/Toggle.styled.tsx
  packages/core/src/components/Toggle/Toggle.tsx
  packages/core/src/components/Toggle/types.ts
Labels: size/S

#360 refactor: change table props name to TableProps
  packages/core/src/components/Table/Body/Body.tsx
  packages/core/src/components/Table/Body/GroupedRow/ContentRow/ContentRow.tsx
  packages/core/src/components/Table/Body/GroupedRow/ContentRow/types.ts
  packages/core/src/components/Table/Body/GroupedRow/GroupedRow.tsx
  packages/core/src/components/Table/Body/GroupedRow/TitleRow/TitleRow.tsx
  packages/core/src/components/Table/Body/GroupedRow/TitleRow/types.ts
  packages/core/src/components/Table/Body/GroupedRow/types.ts
  packages/core/src/components/Table/Body/Row/Row.tsx
  packages/core/src/components/Table/Body/Row/types.ts
  packages/core/src/components/Table/Body/types.ts
  packages/core/src/components/Table/ColumnConfiguration/ColumnConfiguration.tsx
  packages/core/src/components/Table/ColumnConfiguration/types.ts
  packages/core/src/components/Table/GroupCell/GroupCell.styled.tsx
  packages/core/src/components/Table/GroupCell/types.ts
  packages/core/src/components/Table/Head/Head.tsx
  packages/core/src/components/Table/Head/HeadRow/HeadRow.styled.tsx
  packages/core/src/components/Table/Head/HeadRow/types.ts
  packages/core/src/components/Table/Head/types.ts
  packages/core/src/components/Table/Minimap/Minimap.tsx
  packages/core/src/components/Table/Minimap/types.ts
Labels: size/M

#353 refactor: change modal props name to ModalProps
  packages/core/src/components/Modal/Header/types.ts
  packages/core/src/components/Modal/Modal.test.tsx
  packages/core/src/components/Modal/Modal.tsx
  packages/core/src/components/Modal/Popup/Popup.styled.tsx
  packages/core/src/components/Modal/Popup/Popup.test.tsx
  packages/core/src/components/Modal/Popup/Popup.tsx
  packages/core/src/components/Modal/Popup/types.ts
  packages/core/src/components/Modal/types.ts
Labels: size/S

#350 refactor: change label prop name to LabelProps
  packages/core/src/components/Label/Label.styled.tsx
  packages/core/src/components/Label/Label.tsx
  packages/core/src/components/Label/types.ts
Labels: size/S

#332 feat: style updates and added prop to toggle shadow on searchbox
  packages/core/src/components/SearchBox/SearchBox.stories.mdx
  packages/core/src/components/SearchBox/SearchBox.stories.tsx
  packages/core/src/components/SearchBox/SearchBox.styled.tsx
  packages/core/src/components/SearchBox/SearchBox.test.tsx
  packages/core/src/components/SearchBox/SearchBox.tsx
  packages/core/src/components/SearchBox/__snapshots__/SearchBox.test.tsx.snap
  packages/core/src/components/SearchBox/styles/customSearch.tsx
  packages/core/src/components/SearchBox/styles/icons.tsx
  packages/core/src/components/SearchBox/styles/options.tsx
  packages/core/src/components/SearchBox/types.ts
  packages/layout/src/components/SideNav/NavItem/__snapshots__/NavItem.test.tsx.snap
  packages/layout/src/components/SideNav/ToggleSwitch/__snapshots__/ToggleSwitch.test.tsx.snap
  packages/layout/src/components/SideNav/__snapshots__/SideNav.test.tsx.snap
  packages/theme/src/core/searchBox/index.ts
Labels: size/L

#368 fix(icons): executes create-icon command to handle new icon modifications
  packages/icons/src/Icons.stories.mdx
  packages/icons/src/assets/Action/expand_24px_rounded.svg
  packages/icons/src/icons/Action/AccessibilityIcon.tsx
  packages/icons/src/icons/Action/ExpandIcon.tsx
  packages/icons/src/index.ts
Labels: size/L

#370 SW | docs(core): adds docs for Chip component
  packages/core/src/components/Button/Button.stories.mdx
  packages/core/src/components/Chip/Chip.stories.mdx
  packages/core/src/components/Chip/Chip.stories.tsx
Labels: size/M

#367 feat: add the `disabled` prop in breadcrumb item
  packages/core/src/components/Breadcrumb/Breadcrumb.stories.mdx
  packages/core/src/components/Breadcrumb/Item/Item.styled.tsx
  packages/core/src/components/Breadcrumb/Item/Item.tsx
  packages/core/src/components/Breadcrumb/Item/types.ts
  packages/theme/src/core/breadcrumb/index.ts
  packages/theme/src/core/breadcrumb/types.ts
Labels: size/M

#375 fix: remove toast container if there are no toasts available
  packages/core/src/components/ToastContainer/ToastContainer.component.tsx
  packages/core/src/components/ToastContainer/ToastContainer.test.tsx
  packages/core/src/components/ToastContainer/__snapshots__/ToastContainer.test.tsx.snap
Labels: size/XXL

#373 feat: run lint, build & test workflow on pull request as well
  .github/workflows/lint-build-test.yml
Labels: size/XS

#376 feat: ensure text remains visible during webfont load
  packages/core/src/components/CssBaseline/fonts.tsx
Labels: size/XS

#337 feat(forms): add missing HTML5 input types
  packages/forms/src/components/Fields/Fields.components.tsx
  packages/forms/src/components/Form/Form.stories.tsx
  packages/forms/src/components/Form/__snapshots__/Form.test.tsx.snap
  packages/forms/src/components/Form/testSchema.ts
Labels: size/M

#378 docs: Made editorial changes to some pages.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/story.md
  .github/PULL_REQUEST_TEMPLATE.md
  docs/Colors/Colors.stories.mdx
  docs/Introduction.stories.mdx
  packages/core/src/components/Breadcrumb/Breadcrumb.stories.mdx
  packages/core/src/components/Button/Button.stories.mdx
  packages/core/src/components/Card/Card.stories.mdx
  packages/core/src/components/CenterAlignedLoader/CenterAlignedLoader.stories.mdx
Labels: size/M

#371 feat: search box component updates
  packages/core/src/components/SearchBox/__snapshots__/SearchBox.test.tsx.snap
  packages/core/src/components/SearchBox/styles/icons.tsx
  packages/core/src/components/SearchBox/styles/options.tsx
  packages/theme/src/core/searchBox/index.ts
  packages/theme/src/core/searchBox/types.ts
Labels: size/S

#379 feat: updating theme to include searchBox expandIcon active state
  packages/core/src/components/SearchBox/styles/icons.tsx
  packages/theme/src/core/searchBox/index.ts
  packages/theme/src/core/searchBox/types.ts
Labels: size/XS

#380 fix: soft keyboard opening on mobile browser in singleselect component
  packages/core/src/components/SingleSelect/SingleSelect.tsx
  packages/core/src/components/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap
  packages/forms/src/components/Form/__snapshots__/Form.test.tsx.snap
Labels: size/S

#365 feat(core): add a new variant for helper/error text
  .jest-test-results.json
  packages/core/src/components/Calendar/__snapshots__/Calendar.test.tsx.snap
  packages/core/src/components/DatePicker/__snapshots__/DatePicker.test.tsx.snap
  packages/core/src/components/DatePicker/types.ts
  packages/core/src/components/DateRangePicker/DateRangePicker.tsx
  packages/core/src/components/DateRangePicker/DateRangeTextFields/DateRangeTextFields.tsx
  packages/core/src/components/DateRangePicker/DateRangeTextFields/types.ts
  packages/core/src/components/DateRangePicker/__snapshots__/DateRangePicker.test.tsx.snap
  packages/core/src/components/DateRangePicker/types.ts
  packages/core/src/components/HelperAndErrorTextTooltip/HelperAndErrorTextTooltip.stories.mdx
  packages/core/src/components/HelperAndErrorTextTooltip/HelperAndErrorTextTooltip.stories.tsx
  packages/core/src/components/HelperAndErrorTextTooltip/HelperAndErrorTextTooltip.styled.tsx
  packages/core/src/components/HelperAndErrorTextTooltip/HelperAndErrorTextTooltip.tsx
  packages/core/src/components/HelperAndErrorTextTooltip/index.ts
  packages/core/src/components/HelperAndErrorTextTooltip/types.ts
  packages/core/src/components/MultiSelect/MultiSelect.tsx
  packages/core/src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  packages/core/src/components/MultiSelect/types.ts
  packages/core/src/components/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap
  packages/core/src/components/SingleSelect/types.ts
  packages/core/src/components/Table/ActionBar/__snapshots__/ActionBar.test.tsx.snap
  packages/core/src/components/TextField/Styled/CharacterCount.styled.tsx
  packages/core/src/components/TextField/Styled/HelperAndErrorTextTooltipWrapper.styled.tsx
  packages/core/src/components/TextField/Styled/HelperText.styled.tsx
  packages/core/src/components/TextField/Styled/index.ts
  packages/core/src/components/TextField/TextField.test.tsx
  packages/core/src/components/TextField/TextField.tsx
  packages/core/src/components/TextField/__snapshots__/TextField.test.tsx.snap
  packages/core/src/components/TextField/types.ts
  packages/forms/src/components/Fields/Fields.components.tsx
  packages/forms/src/components/Fields/types.ts
  packages/forms/src/components/Form/__snapshots__/Form.test.tsx.snap
  packages/forms/src/components/Form/types.ts
  packages/layout/src/components/SideNav/NavItem/__snapshots__/NavItem.test.tsx.snap
  packages/layout/src/components/SideNav/ToggleSwitch/__snapshots__/ToggleSwitch.test.tsx.snap
  packages/layout/src/components/SideNav/__snapshots__/SideNav.test.tsx.snap
  packages/theme/src/core/helperAndErrorTextTooltip/index.ts
  packages/theme/src/core/helperAndErrorTextTooltip/types.ts
  packages/theme/src/core/index.ts
  packages/theme/src/core/types.ts
  packages/theme/src/types.ts
Labels: size/XXL

#377 feat(layout): new header layout component
  packages/core/src/components/Logo/Logo.stories.mdx
  packages/core/src/components/Logo/Logo.stories.tsx
  packages/core/src/components/Logo/Logo.styled.tsx
  packages/core/src/components/Logo/Logo.test.tsx
  packages/core/src/components/Logo/Logo.tsx
  packages/core/src/components/Logo/assets/MLogo.svg
  packages/core/src/components/Logo/assets/MedlyLogo.svg
  packages/core/src/components/Logo/index.ts
  packages/core/src/components/Logo/types.ts
  packages/core/src/components/index.ts
  packages/layout/src/components/Header/Header.context.tsx
  packages/layout/src/components/Header/Header.stories.mdx
  packages/layout/src/components/Header/Header.stories.tsx
  packages/layout/src/components/Header/Header.styled.tsx
  packages/layout/src/components/Header/Header.test.tsx
  packages/layout/src/components/Header/Header.tsx
  packages/layout/src/components/Header/Nav/Nav.styled.tsx
  packages/layout/src/components/Header/Nav/Nav.test.tsx
  packages/layout/src/components/Header/Nav/Nav.tsx
  packages/layout/src/components/Header/Nav/index.ts
  packages/layout/src/components/Header/NavItem/NavItem.styled.tsx
  packages/layout/src/components/Header/NavItem/index.ts
  packages/layout/src/components/Header/index.ts
  packages/layout/src/components/Header/types.ts
  packages/layout/src/components/SideNav/MedlySidenavHeader/MedlySidenavHeader.styled.tsx
  packages/layout/src/components/SideNav/MedlySidenavHeader/MedlySidenavHeader.test.tsx
  packages/layout/src/components/SideNav/MedlySidenavHeader/MedlySidenavHeader.tsx
  packages/layout/src/components/SideNav/MedlySidenavHeader/__snapshots__/MedlySidenavHeader.test.tsx.snap
  packages/layout/src/components/SideNav/NavItem/__snapshots__/NavItem.test.tsx.snap
  packages/layout/src/components/SideNav/SideNav.stories.mdx
  packages/layout/src/components/SideNav/ToggleSwitch/__snapshots__/ToggleSwitch.test.tsx.snap
  packages/layout/src/components/SideNav/__snapshots__/SideNav.test.tsx.snap
  packages/layout/src/components/SideNav/types.ts
  packages/layout/src/components/index.ts
  packages/theme/src/layout/header/index.ts
  packages/theme/src/layout/header/types.ts
  packages/theme/src/layout/index.ts
  packages/theme/src/layout/types.ts
  packages/theme/src/types.ts
Labels: size/XXL

#383 SW | feat(utils): adds multiple keys press support in `useKeyPress` hook
  package.json
  packages/utils/src/hooks/useKeyPress.ts
  packages/utils/src/hooks/useKeyPress/index.ts
  packages/utils/src/hooks/useKeyPress/useKeyPress.stories.mdx
  packages/utils/src/hooks/useKeyPress/useKeyPress.stories.tsx
  packages/utils/src/hooks/useKeyPress/useKeyPress.styled.tsx
  packages/utils/src/hooks/useKeyPress/useKeyPress.test.tsx
  packages/utils/src/hooks/useKeyPress/useKeyPress.ts
Labels: size/L

#382 feat(core): add custom range selection options in date range picker
  packages/core/src/components/DateRangePicker/CustomDateRangeOptions/CustomDateRangeOptions.styled.tsx
  packages/core/src/components/DateRangePicker/CustomDateRangeOptions/index.ts
  packages/core/src/components/DateRangePicker/DateRangePicker.stories.mdx
  packages/core/src/components/DateRangePicker/DateRangePicker.stories.tsx
  packages/core/src/components/DateRangePicker/DateRangePicker.test.tsx
  packages/core/src/components/DateRangePicker/DateRangePicker.tsx
  packages/core/src/components/DateRangePicker/DateRangeTextFields/DateRangeTextFields.styled.tsx
  packages/core/src/components/DateRangePicker/DateRangeTextFields/DateRangeTextFields.tsx
  packages/core/src/components/DateRangePicker/DateRangeTextFields/types.ts
  packages/core/src/components/DateRangePicker/DateRangeTextFields/useDateRangeTextFieldsHandlers.ts
  packages/core/src/components/DateRangePicker/__snapshots__/DateRangePicker.test.tsx.snap
  packages/core/src/components/DateRangePicker/helpers/dateRangeHelpers.ts
  packages/core/src/components/DateRangePicker/helpers/index.ts
  packages/core/src/components/DateRangePicker/types.ts
  packages/core/src/types.ts
  packages/forms/src/components/Form/__snapshots__/Form.test.tsx.snap
  packages/layout/src/components/SideNav/NavItem/__snapshots__/NavItem.test.tsx.snap
  packages/layout/src/components/SideNav/ToggleSwitch/__snapshots__/ToggleSwitch.test.tsx.snap
  packages/layout/src/components/SideNav/__snapshots__/SideNav.test.tsx.snap
Labels: size/XXL

#384 feat(icons): include fillOpacity prop for SvgIcon
  packages/icons/src/SvgIcon/SvgIcon.styled.tsx
  packages/icons/src/SvgIcon/types.ts
Labels: size/XS

#386 fix(core): fix date range picker min width issue
  packages/core/src/components/DateRangePicker/DateRangePicker.tsx
  packages/core/src/components/DateRangePicker/__snapshots__/DateRangePicker.test.tsx.snap
  packages/forms/src/components/Form/__snapshots__/Form.test.tsx.snap
Labels: size/XL

#387 refactor: use header html tag for Header component
  packages/layout/src/components/Header/Header.styled.tsx
Labels: size/XS

#390 perf(utils): returns function if same key is pressed more than one time
  packages/utils/src/hooks/useKeyPress/useKeyPress.ts
Labels: size/S

#389 feat: add onClick prop in Logo component
  packages/core/src/components/Logo/Logo.styled.tsx
  packages/core/src/components/Logo/Logo.test.tsx
  packages/core/src/components/Logo/Logo.tsx
  packages/core/src/components/Logo/types.ts
  packages/layout/src/components/SideNav/MedlySidenavHeader/__snapshots__/MedlySidenavHeader.test.tsx.snap
Labels: size/M

#388 fix(core): update the start day of the date range's current week selection
  packages/core/src/components/DateRangePicker/DateRangePicker.test.tsx
  packages/core/src/components/DateRangePicker/helpers/dateRangeHelpers.ts
Labels: size/XS

#366 feat(core): update pagination and table theme
  packages/core/src/components/Pagination/Pagination.styled.tsx
  packages/core/src/components/Pagination/Pagination.tsx
  packages/core/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
  packages/core/src/components/Table/Body/Row/Row.styled.tsx
  packages/core/src/components/Table/Body/Row/__snapshots__/Row.test.tsx.snap
  packages/core/src/components/Table/Foot/Foot.styled.tsx
  packages/core/src/components/Table/Table.styled.tsx
  packages/core/src/components/Table/Table.test.tsx
  packages/core/src/components/Table/__snapshots__/Table.test.tsx.snap
  packages/theme/src/core/pagination/index.ts
  packages/theme/src/core/pagination/types.ts
  packages/theme/src/core/table/index.ts
  packages/theme/src/core/table/types.ts
Labels: size/XXL

#385 XS Table fixes
  packages/core/src/components/Table/Body/Row/Row.styled.tsx
  packages/core/src/components/Table/Foot/Foot.styled.tsx
  packages/core/src/components/Table/Foot/Foot.tsx
  packages/core/src/components/Table/Foot/types.ts
  packages/core/src/components/Table/GroupCell/GroupCell.styled.tsx
  packages/core/src/components/Table/GroupCell/types.ts
  packages/core/src/components/Table/Head/Head.tsx
  packages/core/src/components/Table/Head/HeadCell/HeadCell.styled.tsx
  packages/core/src/components/Table/Table.styled.tsx
  packages/core/src/components/Table/Table.tsx
  packages/core/src/components/Table/__snapshots__/Table.test.tsx.snap
  packages/layout/src/components/SideNav/NavItem/__snapshots__/NavItem.test.tsx.snap
  packages/layout/src/components/SideNav/ToggleSwitch/__snapshots__/ToggleSwitch.test.tsx.snap
  packages/layout/src/components/SideNav/__snapshots__/SideNav.test.tsx.snap
Labels: size/L

#394 fix: update component after unmount in useAxios hook
  packages/utils/src/hooks/useAxios/useAxios.ts
Labels: size/S

#395 fix: default color of chevron icon in multiSelect component
  packages/core/src/components/MultiSelect/MultiSelect.styled.tsx
  packages/core/src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  packages/forms/src/components/Form/__snapshots__/Form.test.tsx.snap
Labels: size/M

#391 fix: adding in critical dependency for handleOptionClick
  packages/core/src/components/SearchBox/SearchBox.tsx
Labels: size/XS

#396 fix: add Style attribute in Header component
  packages/layout/src/components/Header/Header.tsx
  packages/layout/src/components/Header/NavItem/NavItem.styled.tsx
Labels: size/XS

#397 fix: error not coming when required prop is provided in SingleSelect …
  packages/core/src/components/SingleSelect/SingleSelect.tsx
  packages/forms/src/components/Form/__snapshots__/Form.test.tsx.snap
Labels: size/XS

#392 feat(layout): allow setting a different height for header in mobile r…
  packages/layout/src/components/Header/Header.stories.mdx
  packages/layout/src/components/Header/Header.styled.tsx
  packages/layout/src/components/Header/NavItem/NavItem.styled.tsx
  packages/theme/src/layout/header/index.ts
  packages/theme/src/layout/header/types.ts
Labels: size/S

#399 fix: Use https for hero image
  README.md
Labels: size/XS

#405 docs: update useAxios docs
  packages/utils/src/hooks/useAxios/useAxios.stories.mdx
Labels: size/XS
