Repository medly/medly-components, pull requests merged in 2021-02, with the labels that each got.

#243 feat(core): add minimap component in table for effortless horizontal scrolling
  .vscode/settings.json
  packages/core/src/components/Table/Body/Body.tsx
  packages/core/src/components/Table/Minimap/Minimap.styled.tsx
  packages/core/src/components/Table/Minimap/Minimap.test.tsx
  packages/core/src/components/Table/Minimap/Minimap.tsx
  packages/core/src/components/Table/Minimap/__snapshots__/Minimap.test.tsx.snap
  packages/core/src/components/Table/Minimap/index.ts
  packages/core/src/components/Table/Minimap/types.ts
  packages/core/src/components/Table/Table.tsx
  packages/core/src/components/Table/__snapshots__/Table.test.tsx.snap
  packages/core/src/components/Table/docs/Table.stories.mdx
  packages/core/src/components/Table/types.ts
  packages/core/src/components/Table/useScrollState.ts
  packages/layout/src/components/SideNav/NavItem/__snapshots__/NavItem.test.tsx.snap
  packages/layout/src/components/SideNav/ToggleSwitch/__snapshots__/ToggleSwitch.test.tsx.snap
  packages/layout/src/components/SideNav/__snapshots__/SideNav.test.tsx.snap
  packages/theme/src/core/table/index.ts
  packages/theme/src/core/table/types.ts
Labels: size/XXL

#246 fix: change default branch name
  .github/workflows/release.yml
Labels: size/XS

#247 fix(core): fix column width size issue on hide/show column from column configuration
  packages/core/src/components/Table/Head/types.ts
  packages/core/src/components/Table/Table.tsx
  packages/core/src/components/Table/helpers.ts
  packages/core/src/components/Table/types.ts
Labels: size/M

#254 feat: add animation in modal desktop version
  packages/core/src/components/Modal/Modal.styled.tsx
  packages/core/src/components/Modal/Popup/Popup.styled.tsx
  packages/core/src/components/Modal/Popup/__snapshots__/Popup.test.tsx.snap
  packages/core/src/components/Modal/__snapshots__/Modal.test.tsx.snap
Labels: size/L

#255 fix(core): fix column separator is getting hidden on hide/show column
  packages/core/src/components/Table/GroupCell/GroupCell.styled.tsx
  packages/core/src/components/Table/GroupCell/__snapshots__/GroupCell.test.tsx.snap
  packages/core/src/components/Table/Head/HeadRow/HeadRow.styled.tsx
  packages/core/src/components/Table/__snapshots__/Table.test.tsx.snap
Labels: size/XL

#257 fix(core): fix minimap styling, add dimension dependencies and modal scroll event propagation
  packages/core/src/components/Modal/useScrollState.ts
  packages/core/src/components/Table/Body/Body.tsx
  packages/core/src/components/Table/Minimap/Minimap.styled.tsx
  packages/core/src/components/Table/Minimap/Minimap.test.tsx
  packages/core/src/components/Table/Minimap/Minimap.tsx
  packages/core/src/components/Table/Minimap/__snapshots__/Minimap.test.tsx.snap
  packages/core/src/components/Table/Minimap/types.ts
Labels: size/L

#258 fix(core): update z-index of toaster component
  packages/core/src/components/ToastContainer/ToastContainer.styled.tsx
  packages/core/src/components/ToastContainer/__snapshots__/ToastContainer.test.tsx.snap
Labels: size/S

#259 fix: row hover action visibility on table when it is loading
  packages/core/src/components/Table/Body/Row/Row.tsx
Labels: size/XS

#260 refactor: add default values of Table props
  packages/core/src/components/Table/Table.tsx
Labels: size/XS
