Repository medly/medly-components, pull requests merged in 2021-12, with the labels that each got.

#548 fix: editing textfield problem due to table keyboard event
  packages/core/src/components/MultiSelect/MultiSelect.test.tsx
  packages/core/src/components/MultiSelect/Options/Options.tsx
  packages/core/src/components/Table/Body/Body.tsx
Labels: size/M

#552 feat: create multi-select option on enter keypress
  packages/core/src/components/MultiSelect/MultiSelect.test.tsx
  packages/core/src/components/MultiSelect/MultiSelect.tsx
  packages/core/src/components/MultiSelect/Options/Options.tsx
  packages/core/src/components/MultiSelect/Options/types.ts
Labels: enhancement, size/M

#551 feat: add Box component
  README.md
  packages/core/package.json
  packages/core/src/components/Box/Box.stories.mdx
  packages/core/src/components/Box/Box.stories.tsx
  packages/core/src/components/Box/Box.styled.tsx
  packages/core/src/components/Box/Box.test.tsx
  packages/core/src/components/Box/Box.tsx
  packages/core/src/components/Box/__snapshots__/Box.test.tsx.snap
  packages/core/src/components/Box/index.ts
  packages/core/src/components/Box/types.ts
  packages/core/src/components/index.ts
  packages/core/src/types.ts
Labels: size/XXL

#555 fix: useStorage eventlistner issue
  packages/utils/src/hooks/useStorage/useStorage.ts
Labels: size/XS

#554 test: add test cases for table foot
  packages/core/src/components/Table/Foot/Foot.test.tsx
  packages/core/src/components/Table/Foot/Foot.tsx
  packages/core/src/components/Table/Foot/__snapshots__/Foot.test.tsx.snap
  packages/core/src/components/Table/__snapshots__/Table.test.tsx.snap
Labels: size/XXL

#556 style: update single select border radius as per new design
  packages/core/src/components/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap
  packages/theme/src/core/singleSelect/index.ts
Labels: size/XS

#559 feat: update header component style as per new style
  packages/core/src/components/Logo/Logo.tsx
  packages/layout/src/components/Header/Header.styled.tsx
  packages/layout/src/components/Header/Header.tsx
  packages/layout/src/components/Header/Nav/Nav.tsx
  packages/layout/src/components/Header/NavItem/NavItem.styled.tsx
  packages/layout/src/components/Header/NavItem/NavItem.test.tsx
  packages/layout/src/components/Header/NavItem/__snapshots__/NavItem.test.tsx.snap
  packages/theme/src/core/colors/types.ts
  packages/theme/src/layout/header/index.ts
  packages/theme/src/layout/header/types.ts
Labels: size/L

#560 fix: fix active tab value for TabList
  packages/core/src/components/Tabs/TabList/TabList.tsx
Labels: size/XS

#563 Update/validator
  packages/core/src/components/Checkbox/Checkbox.tsx
  packages/core/src/components/Checkbox/types.ts
  packages/core/src/components/DatePicker/DatePicker.tsx
  packages/core/src/components/DatePicker/types.ts
  packages/core/src/components/DateRangePicker/DateRangePicker.tsx
  packages/core/src/components/DateRangePicker/DateRangeTextFields/types.ts
  packages/core/src/components/DateRangePicker/DateRangeTextFields/useDateRangeTextFieldsHandlers.ts
  packages/core/src/components/DateRangePicker/types.ts
  packages/core/src/components/TextField/TextField.tsx
  packages/core/src/components/TextField/types.ts
Labels: size/M

#562 feat: add labels for storybook components
  .storybook/main.js
  .storybook/preview.js
  package.json
  packages/core/src/components/CardTable/docs/CardTable.stories.mdx
  packages/core/src/components/Input/Input.stories.mdx
  yarn.lock
Labels: enhancement, size/L

#565 docs: add number type to form docs
  packages/forms/src/components/Form/stories/Form.stories.tsx
Labels: size/XS

#561 feat(core): add props to Accordion component to handle active state f…
  packages/core/src/components/Accordion/Accordion.stories.mdx
  packages/core/src/components/Accordion/Accordion.stories.tsx
  packages/core/src/components/Accordion/Accordion.test.tsx
  packages/core/src/components/Accordion/Accordion.tsx
  packages/core/src/components/Accordion/types.ts
Labels: size/L
