Repository medly/medly-components, pull requests merged in 2021-06, with the labels that each got.

#290 feat: add react 17 also as peer dependency
  package.json
  packages/core/package.json
  packages/forms/package.json
  packages/icons/package.json
  packages/layout/package.json
  packages/loaders/package.json
  packages/utils/package.json
Labels: size/S

#288 fix(core): update multiselect to display option label
  packages/core/src/components/MultiSelect/MultiSelect.stories.tsx
  packages/core/src/components/MultiSelect/MultiSelect.tsx
  packages/core/src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  packages/core/src/components/MultiSelect/helpers.ts
  packages/forms/src/components/Form/__snapshots__/Form.test.tsx.snap
Labels: size/S

#291 PES-1462 Allow button theme to toggle shadow on hover
  packages/core/src/components/Button/Button.test.tsx
  packages/core/src/components/Button/__snapshots__/Button.test.tsx.snap
  packages/core/src/components/Button/styles/outlinedButton.tsx
  packages/core/src/components/Button/styles/solidButton.tsx
  packages/theme/src/core/button/index.ts
  packages/theme/src/core/button/types.ts
Labels: size/L

#293 PES-1463 add 'xs' button size
  packages/core/src/components/Button/Button.stories.mdx
  packages/core/src/components/Button/Button.stories.tsx
  packages/core/src/components/Button/Button.test.tsx
  packages/core/src/components/Button/__snapshots__/Button.test.tsx.snap
  packages/theme/src/core/button/index.ts
  packages/theme/src/core/button/types.ts
Labels: size/L

#295 fix: npm warnings for projects using react 17
  packages/core/package.json
  packages/forms/package.json
  packages/icons/package.json
  packages/layout/package.json
  packages/loaders/package.json
  packages/utils/package.json
  yarn.lock
Labels: size/M

#296 Fixes label overflow issue in textfield label
  packages/core/src/components/DatePicker/__snapshots__/DatePicker.test.tsx.snap
  packages/core/src/components/DateRangePicker/__snapshots__/DateRangePicker.test.tsx.snap
  packages/core/src/components/Modal/Modal.stories.tsx
  packages/core/src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  packages/core/src/components/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap
  packages/core/src/components/TextField/Styled/Label.styled.tsx
  packages/core/src/components/TextField/__snapshots__/TextField.test.tsx.snap
  packages/forms/src/components/Form/__snapshots__/Form.test.tsx.snap
Labels: size/L

#297 fix: focus issue when we select either month or year in single month …
  packages/core/src/components/Calendar/MonthAndYearSelection/MonthAndYearSelection.tsx
  packages/core/src/components/DateRangePicker/DateRangeCalendar/DateRangeCalendar.tsx
Labels: size/S

#298 fix: showing error even if date is filled when required prop is passe…
  packages/core/src/components/DatePicker/DatePicker.tsx
Labels: size/XS

#299 fix(core, forms): updates the z-index values of components
  packages/core/src/components/CenterAlignedLoader/CenterAlignedLoader.styled.tsx
  packages/core/src/components/CenterAlignedLoader/__snapshots__/CenterAlignedLoader.test.tsx.snap
  packages/core/src/components/DatePicker/DatePicker.styled.tsx
  packages/core/src/components/DatePicker/__snapshots__/DatePicker.test.tsx.snap
  packages/core/src/components/DateRangePicker/DateRangeCalendar/DateRangeCalendar.styled.tsx
  packages/core/src/components/DateRangePicker/__snapshots__/DateRangePicker.test.tsx.snap
  packages/core/src/components/Drawer/Drawer.styled.tsx
  packages/core/src/components/Drawer/__snapshots__/Drawer.test.tsx.snap
  packages/core/src/components/MultiSelect/Options/Options.styled.ts
  packages/core/src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  packages/core/src/components/Pagination/PaginationPopup/PaginationPopup.styled.tsx
  packages/core/src/components/Popover/Popup/__snapshots__/Popup.test.tsx.snap
  packages/core/src/components/Popover/Popup/styled/Popup.styled.tsx
  packages/core/src/components/Popover/Popup/styled/WithArrow.tsx
  packages/core/src/components/SearchBox/__snapshots__/SearchBox.test.tsx.snap
  packages/core/src/components/SingleSelect/Options/Options.styled.tsx
  packages/core/src/components/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap
  packages/core/src/components/Table/ActionBar/__snapshots__/ActionBar.test.tsx.snap
  packages/core/src/components/Table/Minimap/Minimap.styled.tsx
  packages/core/src/components/Table/Minimap/__snapshots__/Minimap.test.tsx.snap
  packages/core/src/components/TextField/Styled/CharacterCount.styled.tsx
  packages/core/src/components/TextField/__snapshots__/TextField.test.tsx.snap
  packages/forms/src/components/Form/__snapshots__/Form.test.tsx.snap
  packages/utils/src/helpers/debounce.ts
Labels: size/L

#300 Fix min width issue in all the form fields
  packages/core/src/components/Calendar/__snapshots__/Calendar.test.tsx.snap
  packages/core/src/components/DatePicker/DatePicker.stories.mdx
  packages/core/src/components/DatePicker/DatePicker.tsx
  packages/core/src/components/DatePicker/__snapshots__/DatePicker.test.tsx.snap
  packages/core/src/components/DateRangePicker/__snapshots__/DateRangePicker.test.tsx.snap
  packages/core/src/components/MultiSelect/MultiSelect.stories.mdx
  packages/core/src/components/MultiSelect/MultiSelect.styled.tsx
  packages/core/src/components/MultiSelect/MultiSelect.test.tsx
  packages/core/src/components/MultiSelect/MultiSelect.tsx
  packages/core/src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  packages/core/src/components/MultiSelect/types.ts
  packages/core/src/components/SingleSelect/SingleSelect.stories.mdx
  packages/core/src/components/SingleSelect/SingleSelect.styled.tsx
  packages/core/src/components/SingleSelect/SingleSelect.tsx
  packages/core/src/components/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap
  packages/forms/src/components/Fields/Fields.components.tsx
  packages/forms/src/components/Form/Form.styled.tsx
  packages/forms/src/components/Form/__snapshots__/Form.test.tsx.snap
Labels: size/XL

#301 Fix/sidenav default open prop change
  packages/layout/src/components/SideNav/SideNav.stories.tsx
  packages/layout/src/components/SideNav/SideNav.test.tsx
Labels: size/S

#302 doc(core): added documentation for custom table cell component
  packages/core/src/components/Table/docs/Table.stories.mdx
Labels: size/S

#303 feat(core): Add pressed state to Avatar component
  packages/core/src/components/Avatar/Avatar.styled.tsx
  packages/core/src/components/Avatar/Avatar.test.tsx
  packages/core/src/components/Avatar/Avatar.tsx
  packages/core/src/components/Avatar/__snapshots__/Avatar.test.tsx.snap
  packages/core/src/components/Avatar/types.ts
  packages/theme/src/core/avatar/index.ts
  packages/theme/src/core/avatar/types.ts
Labels: size/L

#304 refactor: remove yarn.lock as well in clean command
  package.json
Labels: size/XS

#305 SW | docs(core): adds table features list with easy navigation
  packages/core/src/components/Table/__snapshots__/Table.test.tsx.snap
  packages/core/src/components/Table/docs/Table.stories.mdx
  packages/core/src/components/Table/docs/Table.stories.tsx
  packages/core/src/components/Table/docs/data.ts
Labels: size/M

#306 SW | docs(core): updates documentation of row selection
  packages/core/src/components/Table/docs/Table.stories.mdx
Labels: size/M
