Repository medly/medly-components, pull requests merged in 2021-10, with the labels that each got.

#469 refactor: mark false positive for sonar regex warning
  packages/core/src/components/Table/helpers.ts
  packages/core/src/components/TextField/getMaskedValue.ts
Labels: size/XS

#468 fix: fix strict null check issue in MultiSelect component
  packages/core/src/components/MultiSelect/InputSuffix/Chip/Chip.styled.ts
  packages/core/src/components/MultiSelect/InputSuffix/Chip/Chip.test.tsx
  packages/core/src/components/MultiSelect/InputSuffix/Chip/Chip.tsx
  packages/core/src/components/MultiSelect/InputSuffix/Chip/types.ts
  packages/core/src/components/MultiSelect/InputSuffix/types.ts
  packages/core/src/components/MultiSelect/MultiSelect.stories.tsx
  packages/core/src/components/MultiSelect/MultiSelect.test.tsx
  packages/core/src/components/MultiSelect/MultiSelect.tsx
  packages/core/src/components/MultiSelect/Options/Chip/Chip.test.tsx
  packages/core/src/components/MultiSelect/Options/Chip/Chip.tsx
  packages/core/src/components/MultiSelect/Options/Chip/types.ts
  packages/core/src/components/MultiSelect/Options/Options.test.tsx
  packages/core/src/components/MultiSelect/Options/types.ts
  packages/core/src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  packages/core/src/components/MultiSelect/types.ts
  packages/core/src/components/Table/Table.tsx
  packages/forms/src/components/Form/Form.test.tsx
  packages/forms/src/components/Form/__snapshots__/Form.test.tsx.snap
Labels: size/L

#471 fix: fix strict null check issue in FileInput, Hidden, Input, Label, …
  packages/core/src/components/FieldWithLabel/types.ts
  packages/core/src/components/FileInput/FileInput.stories.tsx
  packages/core/src/components/FileInput/FileInput.test.tsx
  packages/core/src/components/FileInput/FileInput.tsx
  packages/core/src/components/FileInput/__snapshots__/FileInput.test.tsx.snap
  packages/core/src/components/Hidden/Hidden.test.tsx
  packages/core/src/components/Hidden/HiddenJs/HiddenJs.test.tsx
  packages/core/src/components/Input/Input.stories.tsx
  packages/core/src/components/Input/Input.styled.tsx
  packages/core/src/components/Input/Input.tsx
  packages/core/src/components/Input/types.ts
  packages/core/src/components/Label/Label.styled.tsx
  packages/core/src/components/Label/Label.tsx
  packages/core/src/components/Label/types.ts
  packages/core/src/components/List/List.stories.tsx
  packages/core/src/components/List/types.ts
  packages/core/src/components/Modal/Actions/Actions.test.tsx
  packages/core/src/components/Modal/Content/Content.tsx
  packages/core/src/components/Modal/Header/Header.tsx
  packages/core/src/components/Modal/Modal.context.ts
  packages/core/src/components/Modal/Modal.test.tsx
  packages/core/src/components/Modal/Modal.tsx
  packages/core/src/components/Modal/Popup/types.ts
  packages/core/src/components/Modal/__snapshots__/Modal.test.tsx.snap
  packages/core/src/components/Modal/types.ts
  packages/forms/src/components/Form/__snapshots__/Form.test.tsx.snap
  packages/markdown/package.json
Labels: size/L

#473 refactor(markdown): extract out tomorrow prism theme
  packages/markdown/src/components/MarkdownContent/CodeBlock.tsx
  packages/markdown/src/components/MarkdownContent/tomorrow.ts
Labels: design changes, size/L

#470 Feat/add calendar icon position support
  packages/core/src/components/DatePicker/DatePicker.stories.mdx
  packages/core/src/components/DatePicker/DatePicker.stories.tsx
  packages/core/src/components/DatePicker/DatePicker.test.tsx
  packages/core/src/components/DatePicker/DatePicker.tsx
  packages/core/src/components/DatePicker/__snapshots__/DatePicker.test.tsx.snap
  packages/core/src/components/DatePicker/types.ts
Labels: size/XL, hacktoberest-accepted

#474 fix: fix strict null issue in Drawer and DialogBox component
  packages/core/src/components/DialogBox/Actions/Actions.test.tsx
  packages/core/src/components/DialogBox/DialogBox.test.tsx
  packages/core/src/components/DialogBox/DialogBox.tsx
  packages/core/src/components/DialogBox/Popup/types.ts
  packages/core/src/components/DialogBox/types.ts
  packages/core/src/components/Drawer/Content/Content.tsx
  packages/core/src/components/Drawer/Drawer.context.tsx
  packages/core/src/components/Drawer/Drawer.stories.tsx
  packages/core/src/components/Drawer/Drawer.styled.tsx
  packages/core/src/components/Drawer/Drawer.test.tsx
  packages/core/src/components/Drawer/Drawer.tsx
  packages/core/src/components/Drawer/Header/Header.tsx
  packages/core/src/components/Drawer/Header/__snapshots__/Header.test.tsx.snap
  packages/core/src/components/Drawer/__snapshots__/Drawer.test.tsx.snap
  packages/core/src/components/Drawer/types.ts
  packages/core/src/components/Modal/Modal.context.ts
Labels: size/L

#467 docs: Made editorial changes to Accordion.stories.mdx file
  packages/core/src/components/Accordion/Accordion.stories.mdx
  packages/core/src/components/Avatar/Avatar.stories.mdx
Labels: size/S

#475 fix: strict null check issue in DatePicker and DateRangePicker component
  packages/core/src/components/Calendar/Calendar.test.tsx
  packages/core/src/components/Calendar/Calendar.tsx
  packages/core/src/components/Calendar/MonthAndYearSelection/MonthAndYearSelection.tsx
  packages/core/src/components/Calendar/MonthAndYearSelection/types.ts
  packages/core/src/components/Calendar/__snapshots__/Calendar.test.tsx.snap
  packages/core/src/components/Calendar/helper.ts
  packages/core/src/components/Calendar/types.ts
  packages/core/src/components/DatePicker/DatePicker.stories.tsx
  packages/core/src/components/DatePicker/DatePicker.test.tsx
  packages/core/src/components/DatePicker/DatePicker.tsx
  packages/core/src/components/DatePicker/__snapshots__/DatePicker.test.tsx.snap
  packages/core/src/components/DatePicker/types.ts
  packages/core/src/components/DateRangePicker/DateRangeCalendar/DateRangeCalendar.tsx
  packages/core/src/components/DateRangePicker/DateRangeCalendar/Month/Month.tsx
  packages/core/src/components/DateRangePicker/DateRangeCalendar/Month/Styled/Date.styled.tsx
  packages/core/src/components/DateRangePicker/DateRangeCalendar/Month/types.ts
  packages/core/src/components/DateRangePicker/DateRangeCalendar/types.ts
  packages/core/src/components/DateRangePicker/DateRangePicker.test.tsx
  packages/core/src/components/DateRangePicker/DateRangePicker.tsx
  packages/core/src/components/DateRangePicker/DateRangeTextFields/DateRangeTextFields.styled.tsx
  packages/core/src/components/DateRangePicker/DateRangeTextFields/DateRangeTextFields.tsx
  packages/core/src/components/DateRangePicker/DateRangeTextFields/InputSeparator/types.ts
  packages/core/src/components/DateRangePicker/DateRangeTextFields/types.ts
  packages/core/src/components/DateRangePicker/DateRangeTextFields/useDateRangeTextFieldsHandlers.ts
  packages/core/src/components/DateRangePicker/__snapshots__/DateRangePicker.test.tsx.snap
  packages/forms/src/components/Form/__snapshots__/Form.test.tsx.snap
Labels: size/XL

#476 fix: strict null issue for Accordion, Button, Chip, Card and Card Tab…
  docs/Colors/Colors.stories.tsx
  packages/core/src/components/Accordion/Accordion.tsx
  packages/core/src/components/Accordion/AccordionContext.tsx
  packages/core/src/components/Accordion/types.ts
  packages/core/src/components/Avatar/Avatar.stories.tsx
  packages/core/src/components/Avatar/Avatar.styled.tsx
  packages/core/src/components/Avatar/Avatar.tsx
  packages/core/src/components/Avatar/types.ts
  packages/core/src/components/Button/Button.stories.tsx
  packages/core/src/components/Button/Button.styled.tsx
  packages/core/src/components/Button/Button.test.tsx
  packages/core/src/components/Button/Button.tsx
  packages/core/src/components/Button/Loader/types.ts
  packages/core/src/components/Button/styles/flatButton.tsx
  packages/core/src/components/Button/styles/outlinedButton.tsx
  packages/core/src/components/Button/styles/solidButton.tsx
  packages/core/src/components/Card/Card.styled.tsx
  packages/core/src/components/Card/Card.test.tsx
  packages/core/src/components/Card/types.ts
  packages/core/src/components/CardTable/Body/Body.tsx
  packages/core/src/components/CardTable/Body/Cell/Cell.test.tsx
  packages/core/src/components/CardTable/Body/Cell/Cell.tsx
  packages/core/src/components/CardTable/Body/Cell/types.ts
  packages/core/src/components/CardTable/Body/Row/types.ts
  packages/core/src/components/CardTable/Body/__snapshots__/Body.test.tsx.snap
  packages/core/src/components/CardTable/Head/Head.tsx
  packages/core/src/components/CardTable/Head/HeadCell/HeadCell.test.tsx
  packages/core/src/components/CardTable/Head/HeadCell/HeadCell.tsx
  packages/core/src/components/CardTable/Head/HeadCell/types.ts
  packages/core/src/components/CardTable/Head/types.ts
  packages/core/src/components/Checkbox/Checkbox.stories.tsx
  packages/core/src/components/Checkbox/Checkbox.styled.tsx
  packages/core/src/components/Checkbox/Checkbox.tsx
  packages/core/src/components/Checkbox/checkbox.test.tsx
  packages/core/src/components/Checkbox/types.ts
  packages/core/src/components/CheckboxGroup/CheckboxGroup.stories.tsx
  packages/core/src/components/CheckboxGroup/CheckboxGroup.test.tsx
  packages/core/src/components/CheckboxGroup/CheckboxGroup.tsx
  packages/core/src/components/CheckboxGroup/getValuesFromOptions.ts
  packages/core/src/components/CheckboxGroup/types.ts
  packages/core/src/components/Chip/Chip.stories.tsx
  packages/core/src/components/Chip/Chip.styled.tsx
  packages/core/src/components/Chip/Chip.test.tsx
  packages/core/src/components/Chip/Chip.tsx
  packages/core/src/components/Chip/types.ts
  packages/core/src/components/Drawer/Drawer.stories.tsx
  packages/core/src/components/Tabs/types.ts
  packages/theme/src/core/button/types.ts
  packages/utils/src/types/WithStyle.ts
  packages/utils/src/types/WithThemeProp.ts
  tsconfig.json
Labels: size/L

#472 Feat: Change background color for flat variant of tab
  packages/core/src/components/Tabs/Tab/Tab.styled.tsx
  packages/core/src/components/Tabs/Tab/__snapshots__/Tab.test.tsx.snap
  packages/core/src/components/Tabs/TabList/__snapshots__/TabList.test.tsx.snap
  packages/core/src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
Labels: hacktoberfest-accepted, size/M

#478 Markdown: Add allowElements props
  packages/markdown/src/components/MarkdownContent/MarkdownContent.stories.mdx
  packages/markdown/src/components/MarkdownContent/MarkdownContent.tsx
  packages/markdown/src/components/MarkdownContent/types.ts
Labels: size/S

#477 feat(core): fix number field to display int 0
  packages/forms/src/components/Fields/Fields.components.tsx
Labels: size/XS

#498 feat: Function to be called after the calendar popup closes
  packages/core/src/components/DateRangePicker/DateRangePicker.stories.mdx
  packages/core/src/components/DateRangePicker/DateRangePicker.test.tsx
  packages/core/src/components/DateRangePicker/DateRangePicker.tsx
  packages/core/src/components/DateRangePicker/types.ts
Labels: hacktoberfest-accepted, size/M

#502 doc: add documentation for useWindowSize in utils package
  packages/utils/src/hooks/useWindowSize/index.ts
  packages/utils/src/hooks/useWindowSize/useWindowSize.stories.mdx
  packages/utils/src/hooks/useWindowSize/useWindowSize.test.tsx
  packages/utils/src/hooks/useWindowSize/useWindowSize.ts
Labels: hacktoberfest-accepted, size/M
