Repository medly/medly-components, pull requests merged in 2021-11, with the labels that each got.

#497 docs(utils): add documentation and tests for useOuterClickNotifier (#441)
  packages/utils/src/hooks/useOuterClickNotifier/index.ts
  packages/utils/src/hooks/useOuterClickNotifier/useOuterClickNotifier.stories.mdx
  packages/utils/src/hooks/useOuterClickNotifier/useOuterClickNotifier.test.tsx
  packages/utils/src/hooks/useOuterClickNotifier/useOuterClickNotifier.ts
Labels: hacktoberfest-accepted, size/L

#505 Add infinite scroll to table component
  packages/core/src/components/Table/Table.styled.tsx
  packages/core/src/components/Table/Table.tsx
  packages/core/src/components/Table/docs/Table.stories.mdx
  packages/core/src/components/Table/types.ts
  packages/core/src/components/Table/useScrollState.ts
Labels: enhancement, size/L

#503 docs(utils): add documentation for InjectClassName in utils package
  packages/utils/src/components/InjectClassName/InjectClassName.stories.mdx
Labels: size/M

#514 docs(core): update withCharacterCount prop description
  packages/core/src/components/TextField/types.ts
Labels: size/XS

#506 feat: use new JSX transform
  .storybook/main.js
  babel.config.js
  package.json
  packages/core/src/components/Calendar/__snapshots__/Calendar.test.tsx.snap
  packages/core/src/components/DatePicker/__snapshots__/DatePicker.test.tsx.snap
  packages/core/src/components/DateRangePicker/__snapshots__/DateRangePicker.test.tsx.snap
  packages/core/src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  packages/core/src/components/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap
  packages/core/src/components/Table/__snapshots__/Table.test.tsx.snap
  packages/core/src/components/TextField/__snapshots__/TextField.test.tsx.snap
  packages/forms/src/components/Form/__snapshots__/Form.test.tsx.snap
  packages/layout/src/components/SideNav/__snapshots__/SideNav.test.tsx.snap
  yarn.lock
Labels: size/XL

#515 feat(core): `field` value in tableConfig to accept dot notation
  packages/core/src/components/Table/Body/Row/Row.tsx
  packages/core/src/components/Table/docs/filterData.ts
  packages/core/src/components/Table/helpers.ts
Labels: enhancement, size/S

#518 fix: set babel plugin-transform-react-jsx runtime to automatic
  babel.config.js
Labels: bug, size/XS

#517 Remove react imports: loaders
  packages/loaders/src/LoaderContainer/LoaderContainer.tsx
  packages/loaders/src/Loaders.stories.tsx
  packages/loaders/src/loaders/CircleLoader.tsx
  packages/loaders/src/loaders/ConcentricCircleLoader.tsx
  packages/loaders/src/loaders/DotsBouncingLoader.tsx
  packages/loaders/src/loaders/DotsLoader.tsx
Labels: enhancement, size/S

#523 Remove react imports: layout
  packages/layout/src/components/Header/Header.context.tsx
  packages/layout/src/components/Header/Header.test.tsx
  packages/layout/src/components/Header/Header.tsx
  packages/layout/src/components/Header/Nav/Nav.test.tsx
  packages/layout/src/components/Header/Nav/Nav.tsx
  packages/layout/src/components/Header/types.ts
  packages/layout/src/components/SideNav/MedlySidenavHeader/MedlySidenavHeader.test.tsx
  packages/layout/src/components/SideNav/MedlySidenavHeader/MedlySidenavHeader.tsx
  packages/layout/src/components/SideNav/NavGroup/NavGroup.tsx
  packages/layout/src/components/SideNav/NavItem/NavItem.test.tsx
  packages/layout/src/components/SideNav/NavItem/NavItem.tsx
  packages/layout/src/components/SideNav/NavList/NavList.test.tsx
  packages/layout/src/components/SideNav/SideNav.context.tsx
  packages/layout/src/components/SideNav/SideNav.stories.tsx
  packages/layout/src/components/SideNav/SideNav.test.tsx
  packages/layout/src/components/SideNav/SideNav.tsx
  packages/layout/src/components/SideNav/ToggleSwitch/ToggleSwitch.test.tsx
  packages/layout/src/components/SideNav/ToggleSwitch/ToggleSwitch.tsx
  packages/layout/src/components/SideNav/types.ts
  packages/layout/src/components/SidePanel/SidePanel.test.tsx
Labels: enhancement, size/M

#522 Remove react imports: utils
  packages/utils/src/components/InjectClassName/InjectClassName.test.tsx
  packages/utils/src/components/InjectClassName/InjectClassName.tsx
  packages/utils/src/hooks/useAxios/useAxios.test.tsx
  packages/utils/src/hooks/useKeyPress/useKeyPress.stories.tsx
  packages/utils/src/hooks/useKeyPress/useKeyPress.test.tsx
  packages/utils/src/hooks/useMediaQuery/useMediaQuery.ts
  packages/utils/src/hooks/useOuterClickNotifier/useOuterClickNotifier.test.tsx
  packages/utils/src/hooks/useOuterClickNotifier/useOuterClickNotifier.ts
  packages/utils/src/hooks/useSWRAxios/useSWRAxios.test.tsx
  packages/utils/src/hooks/useStorage/useStorage.test.tsx
  packages/utils/src/hooks/useWindowSize/useWindowSize.test.tsx
  packages/utils/src/style/centerAligned/centerAligned.test.tsx
  packages/utils/src/style/getFontStyle/getFontStyle.test.tsx
  packages/utils/src/test-utils.tsx
  packages/utils/src/types/HTMLProps.ts
Labels: enhancement, size/M

#524 refactor: updateNestedValue function to accept any type
  packages/utils/src/helpers/updateNestedValue/updateNestedValue.test.ts
  packages/utils/src/helpers/updateNestedValue/updateNestedValue.ts
Labels: size/XS

#520 Remove react imports: forms
  packages/forms/src/components/Actions/Actions.test.tsx
  packages/forms/src/components/Actions/Actions.tsx
  packages/forms/src/components/Fields/Fields.components.tsx
  packages/forms/src/components/Form/Form.test.tsx
  packages/forms/src/components/Form/Form.tsx
  packages/forms/src/components/Form/stories/AddPhoneNumber.tsx
  packages/forms/src/components/Form/stories/CustomPhoneField.tsx
  packages/forms/src/components/Form/stories/Form.stories.tsx
Labels: enhancement, size/M

#521 Remove react imports: markdown
  packages/markdown/src/components/MarkdownContent/CodeBlock.tsx
  packages/markdown/src/components/MarkdownContent/MarkdownContent.tsx
  packages/markdown/src/components/MarkdownContent/Youtube.tsx
Labels: enhancement, size/S

#525 feat: add new colors
  packages/theme/src/core/colors/apricot.ts
  packages/theme/src/core/colors/blue.ts
  packages/theme/src/core/colors/blush.ts
  packages/theme/src/core/colors/classyGreen.ts
  packages/theme/src/core/colors/everGreen.ts
  packages/theme/src/core/colors/green.ts
  packages/theme/src/core/colors/heartbeat.ts
  packages/theme/src/core/colors/index.ts
  packages/theme/src/core/colors/medlyGreen.ts
  packages/theme/src/core/colors/periwinkle.ts
  packages/theme/src/core/colors/red.ts
  packages/theme/src/core/colors/types.ts
  packages/theme/src/core/colors/yellow.ts
Labels: size/M

#526 docs: add docs for useCombinedRefs
  packages/utils/src/hooks/useCombinedRefs/index.ts
  packages/utils/src/hooks/useCombinedRefs/useCombinedRefs.stories.mdx
  packages/utils/src/hooks/useCombinedRefs/useCombinedRefs.ts
Labels: documentation, size/S

#527 docs: add docs for useUpdateEffect
  packages/utils/src/hooks/useUpdateEffect/index.ts
  packages/utils/src/hooks/useUpdateEffect/useUpdateEffect.stories.mdx
  packages/utils/src/hooks/useUpdateEffect/useUpdateEffect.ts
  packages/utils/src/hooks/useWindowSize.ts
Labels: documentation, size/M

#528 fix(core): fix table select all issue when rowSelectionDisableKey is not provided
  packages/core/src/components/Table/useRowSelector.ts
Labels: size/XS

#532 refactor: update TextField Variant "Fusion" Border Radius
  packages/core/src/components/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap
  packages/core/src/components/TextField/__snapshots__/TextField.test.tsx.snap
  packages/theme/src/core/textField/index.ts
Labels: size/L

#533 refactor: update hex of rgb color
  packages/core/src/components/Avatar/__snapshots__/Avatar.test.tsx.snap
  packages/core/src/components/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap
  packages/core/src/components/Button/__snapshots__/Button.test.tsx.snap
  packages/core/src/components/Calendar/__snapshots__/Calendar.test.tsx.snap
  packages/core/src/components/CardTable/Head/HeadCell/__snapshots__/HeadCell.test.tsx.snap
  packages/core/src/components/CardTable/Head/__snapshots__/Head.test.tsx.snap
  packages/core/src/components/CardTable/__snapshots__/CardTable.test.tsx.snap
  packages/core/src/components/CenterAlignedLoader/__snapshots__/CenterAlignedLoader.test.tsx.snap
  packages/core/src/components/Checkbox/__snapshots__/checkbox.test.tsx.snap
  packages/core/src/components/Checkbox/checkbox.test.tsx
  packages/core/src/components/CheckboxGroup/CheckboxGroup.test.tsx
  packages/core/src/components/CheckboxGroup/__snapshots__/CheckboxGroup.test.tsx.snap
  packages/core/src/components/Chip/__snapshots__/Chip.test.tsx.snap
  packages/core/src/components/DatePicker/__snapshots__/DatePicker.test.tsx.snap
  packages/core/src/components/DateRangePicker/__snapshots__/DateRangePicker.test.tsx.snap
  packages/core/src/components/Drawer/Header/__snapshots__/Header.test.tsx.snap
  packages/core/src/components/Drawer/__snapshots__/Drawer.test.tsx.snap
  packages/core/src/components/Modal/__snapshots__/Modal.test.tsx.snap
  packages/core/src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  packages/core/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
  packages/core/src/components/Radio/__snapshots__/radio.test.tsx.snap
  packages/core/src/components/RadioGroup/RadioGroup.test.tsx
  packages/core/src/components/RadioGroup/__snapshots__/RadioGroup.test.tsx.snap
  packages/core/src/components/SearchBox/__snapshots__/SearchBox.test.tsx.snap
  packages/core/src/components/SingleSelect/SingleSelect.test.tsx
  packages/core/src/components/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap
  packages/core/src/components/Table/ActionBar/__snapshots__/ActionBar.test.tsx.snap
  packages/core/src/components/Table/Body/Cell/__snapshots__/Cell.test.tsx.snap
  packages/core/src/components/Table/Minimap/__snapshots__/Minimap.test.tsx.snap
  packages/core/src/components/Table/__snapshots__/Table.test.tsx.snap
  packages/core/src/components/Tabs/Tab/__snapshots__/Tab.test.tsx.snap
  packages/core/src/components/Tabs/TabList/__snapshots__/TabList.test.tsx.snap
  packages/core/src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
  packages/core/src/components/TextField/__snapshots__/TextField.test.tsx.snap
  packages/core/src/components/Toast/__snapshots__/Toast.test.tsx.snap
  packages/core/src/components/ToastContainer/__snapshots__/ToastContainer.test.tsx.snap
  packages/forms/src/components/Actions/__snapshots__/Actions.test.tsx.snap
  packages/forms/src/components/Form/__snapshots__/Form.test.tsx.snap
  packages/layout/src/components/SideNav/NavItem/__snapshots__/NavItem.test.tsx.snap
  packages/layout/src/components/SideNav/__snapshots__/SideNav.test.tsx.snap
  packages/theme/src/core/colors/blue.ts
  packages/theme/src/core/colors/green.ts
  packages/theme/src/core/colors/red.ts
Labels: size/XXL

#534 fix: selecting option with numeric value
  packages/core/src/components/MultiSelect/MultiSelect.test.tsx
  packages/core/src/components/MultiSelect/Options/Options.tsx
Labels: size/S

#529 Add docs for HTML props and withStyle
  packages/utils/src/types/HTMLProps/HTMLProps.stories.mdx
  packages/utils/src/types/HTMLProps/HTMLProps.ts
  packages/utils/src/types/HTMLProps/index.ts
  packages/utils/src/types/WithStyle/WithStyle.stories.mdx
  packages/utils/src/types/WithStyle/WithStyle.ts
  packages/utils/src/types/WithStyle/index.ts
  packages/utils/src/types/index.ts
Labels: documentation, size/M

#535 feat: add freezePosition prop to tableColumnConfig
  packages/core/src/components/Table/Body/Cell/Styled/Cell.styled.tsx
  packages/core/src/components/Table/Body/Cell/types.ts
  packages/core/src/components/Table/types.ts
Labels: enhancement, size/S

#538 DS | Editorial Changes
  packages/core/src/components/Chip/Chip.stories.mdx
  packages/core/src/components/CssBaseline/CssBaseline.stories.mdx
  packages/core/src/components/DatePicker/DatePicker.stories.mdx
  packages/core/src/components/DatePicker/types.ts
  packages/core/src/components/DateRangePicker/DateRangePicker.stories.mdx
Labels: size/M

#536 DS | Edit language
  packages/core/src/components/CheckboxGroup/CheckboxGroup.stories.mdx
  packages/core/src/components/DatePicker/types.ts
  packages/core/src/components/DateRangePicker/DateRangePicker.stories.mdx
Labels: size/S

#539 feat: Multi select component to have creatable options
  packages/core/src/components/MultiSelect/MultiSelect.stories.mdx
  packages/core/src/components/MultiSelect/MultiSelect.test.tsx
  packages/core/src/components/MultiSelect/MultiSelect.tsx
  packages/core/src/components/MultiSelect/Options/Chip/Chip.tsx
  packages/core/src/components/MultiSelect/Options/Options.tsx
  packages/core/src/components/MultiSelect/Options/types.ts
  packages/core/src/components/MultiSelect/helpers.ts
  packages/core/src/components/MultiSelect/types.ts
  packages/core/src/components/SingleSelect/Options/Option/Option.tsx
Labels: enhancement, size/L

#540 feat: add hideUnderline prop to toggle flat variant button text underline
  packages/core/src/components/Button/Button.stories.mdx
  packages/core/src/components/Button/Button.test.tsx
  packages/core/src/components/Button/__snapshots__/Button.test.tsx.snap
  packages/core/src/components/Button/styles/flatButton.tsx
  packages/core/src/components/Button/types.ts
Labels: size/L

#541 fix: table cell shrinking issue on resizing any column
  packages/core/src/components/Table/Head/HeadCell/HeadCell.tsx
Labels: size/XS

#542 feat: Add keyboard navigation to table component
  packages/core/src/components/Table/Body/Body.tsx
  packages/core/src/components/Table/Body/Cell/RowActionsCell/RowActionsCell.styled.tsx
  packages/core/src/components/Table/Body/Cell/RowActionsCell/RowActionsCell.tsx
  packages/core/src/components/Table/Body/Cell/RowActionsCell/types.ts
  packages/core/src/components/Table/Body/Row/Row.styled.tsx
  packages/core/src/components/Table/Body/Row/Row.tsx
  packages/core/src/components/Table/Body/Row/types.ts
  packages/core/src/components/Table/Body/types.ts
  packages/core/src/components/Table/Table.tsx
  packages/core/src/components/Table/docs/Table.stories.mdx
  packages/core/src/components/Table/types.ts
Labels: enhancement, size/L

#543 fix: change width to `fit-content` of the flat variant of single select
  packages/core/src/components/Calendar/__snapshots__/Calendar.test.tsx.snap
  packages/core/src/components/DatePicker/__snapshots__/DatePicker.test.tsx.snap
  packages/core/src/components/DateRangePicker/__snapshots__/DateRangePicker.test.tsx.snap
  packages/core/src/components/SingleSelect/SingleSelect.tsx
  packages/core/src/components/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap
Labels: size/M

#544 fix: add left and right arrow to expand and collapse row
  packages/core/src/components/Table/Body/Body.tsx
  packages/core/src/components/Table/Body/Row/Row.styled.tsx
  packages/core/src/components/Table/Body/Row/Row.tsx
  packages/core/src/components/Table/Body/Row/types.ts
  packages/core/src/components/Table/Body/types.ts
  packages/core/src/components/Table/Table.tsx
  packages/core/src/components/Table/constants.ts
  packages/core/src/components/Table/context/TableComponentsCommonProps.context.tsx
  packages/core/src/components/Table/docs/Table.stories.mdx
  packages/core/src/components/Table/types.ts
Labels: size/M

#545 fix: fix multiselect tests
  packages/core/src/components/MultiSelect/MultiSelect.test.tsx
Labels: size/XS

#546 fix: the content to be passed to onChange prop of MultiSelect component
  packages/core/src/components/MultiSelect/MultiSelect.test.tsx
  packages/core/src/components/MultiSelect/Options/Options.tsx
  packages/core/src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
Labels: size/XXL

#547 style: update border radius of modal and dialog box
  packages/core/src/components/DialogBox/Popup/Popup.styled.tsx
  packages/core/src/components/DialogBox/Popup/__snapshots__/Popup.test.tsx.snap
  packages/core/src/components/DialogBox/__snapshots__/DialogBox.test.tsx.snap
  packages/core/src/components/Modal/Popup/__snapshots__/Popup.test.tsx.snap
  packages/core/src/components/Modal/__snapshots__/Modal.test.tsx.snap
  packages/theme/src/core/dialog-box/index.ts
  packages/theme/src/core/modal/index.ts
Labels: size/M
