Repository medly/medly-components, pull requests merged in 2022-02, with the labels that each got.

#582 fix: options id issue of multiselect component
  packages/core/src/components/MultiSelect/MultiSelect.test.tsx
  packages/core/src/components/MultiSelect/Options/Options.tsx
Labels: size/XS

#584 feat(core): add noResutRowText prop in table
  packages/core/src/components/Table/Body/Body.tsx
  packages/core/src/components/Table/Table.test.tsx
  packages/core/src/components/Table/types.ts
Labels: size/S

#585 feat: add functionality to add custom header and message component in…
  packages/core/src/components/Toast/Toast.stories.mdx
  packages/core/src/components/Toast/Toast.test.tsx
  packages/core/src/components/Toast/Toast.tsx
  packages/core/src/components/Toast/__snapshots__/Toast.test.tsx.snap
  packages/core/src/components/Toast/types.ts
  packages/core/src/components/ToastContainer/__snapshots__/ToastContainer.test.tsx.snap
Labels: size/M

#592 fix: onSearch method not getting called on enter keypress
  packages/core/src/components/SearchBox/SearchBox.tsx
Labels: bug, size/S

#593 fix: search component breaks after right arrow key press
  packages/core/src/components/SingleSelect/useKeyboardNavigation.tsx
Labels: bug, size/XS
