Repository medly/medly-components, pull requests merged in 2022-07, with the labels that each got.

#683 fix: should not close modal on clicking on modal
  packages/core/src/components/Modal/Modal.test.tsx
  packages/core/src/components/Modal/Modal.tsx
  packages/core/src/components/Modal/Popup/Popup.tsx
Labels: bug, size/S

#689 fix: modal close issue on click on outside of modal
  packages/core/src/components/Modal/Modal.tsx
  packages/core/src/components/Modal/Popup/Popup.tsx
Labels: size/S

#685 fix(core): DatePicker is not reseting the text field value when the `prop` value is `null`
  packages/core/src/components/DatePicker/DatePicker.tsx
Labels: size/XS
