Repository medly/medly-components, pull requests merged in 2022-03, with the labels that each got.

#599 fix: use id in toggle
  packages/core/src/components/Toggle/Toggle.test.tsx
  packages/core/src/components/Toggle/Toggle.tsx
  packages/core/src/components/Toggle/__snapshots__/Toggle.test.tsx.snap
Labels: size/M

#596 docs: update docs for List, Modal, Pagination and popover component
  packages/core/src/components/List/List.stories.mdx
  packages/core/src/components/Modal/Modal.stories.mdx
  packages/core/src/components/Modal/types.ts
  packages/core/src/components/Pagination/Pagination.stories.mdx
  packages/core/src/components/Popover/Popover.stories.mdx
Labels: size/M

#595 docs: update docs of HelperAndErrorTextTooltip, Input, Label & Link component
  packages/core/src/components/HelperAndErrorTextTooltip/HelperAndErrorTextTooltip.stories.mdx
  packages/core/src/components/HelperAndErrorTextTooltip/types.ts
  packages/core/src/components/Input/Input.stories.mdx
  packages/core/src/components/Input/types.ts
  packages/core/src/components/Label/Label.stories.mdx
  packages/core/src/components/Label/types.ts
  packages/core/src/components/Link/Link.stories.mdx
  packages/core/src/components/Link/types.ts
Labels: size/M

#598 docs: update Radio and RadioGroup components docs
  packages/core/src/components/Radio/Radio.stories.mdx
  packages/core/src/components/Radio/types.ts
  packages/core/src/components/RadioGroup/RadioGroup.stories.mdx
  packages/core/src/components/RadioGroup/types.ts
Labels: size/M

#600 fix: fix for shadow issue on modal component
  packages/core/src/components/Drawer/Drawer.test.tsx
  packages/core/src/components/Drawer/__snapshots__/Drawer.test.tsx.snap
  packages/core/src/components/Modal/Modal.test.tsx
  packages/core/src/components/Modal/Modal.tsx
  packages/core/src/components/Modal/__snapshots__/Modal.test.tsx.snap
  packages/core/src/components/Modal/useScrollState.ts
Labels: size/S

#594 docs: update DatePicker, Drawer and FileInput component
  packages/core/src/components/DatePicker/DatePicker.stories.mdx
  packages/core/src/components/DatePicker/types.ts
  packages/core/src/components/DialogBox/DialogBox.stories.mdx
  packages/core/src/components/Drawer/Drawer.stories.mdx
  packages/core/src/components/FileInput/FileInput.stories.mdx
  packages/core/src/components/FileInput/types.ts
Labels: size/M

#588 docs: update github docs and other multiple component docs
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
  packages/core/src/components/Accordion/Accordion.stories.mdx
  packages/core/src/components/Avatar/Avatar.stories.mdx
  packages/core/src/components/Box/Box.stories.mdx
  packages/core/src/components/Box/types.ts
  packages/core/src/components/Breadcrumb/Breadcrumb.stories.mdx
  packages/core/src/components/Breadcrumb/types.ts
  packages/core/src/components/Button/Button.stories.mdx
  packages/core/src/components/Button/types.ts
  packages/core/src/components/Card/Card.stories.mdx
  packages/core/src/components/Card/types.ts
  packages/core/src/components/CenterAlignedLoader/CenterAlignedLoader.stories.mdx
  packages/core/src/components/CenterAlignedLoader/types.ts
  packages/core/src/components/Checkbox/Checkbox.stories.mdx
  packages/core/src/components/Checkbox/types.ts
  packages/core/src/components/CheckboxGroup/CheckboxGroup.stories.mdx
  packages/core/src/components/CheckboxGroup/types.ts
  packages/core/src/components/Chip/Chip.stories.mdx
  packages/core/src/components/Chip/types.ts
  packages/core/src/components/CssBaseline/CssBaseline.stories.mdx
Labels: size/L

#605 Fix for modal shadow issue
  packages/core/src/components/Modal/useScrollState.ts
Labels: size/XS

#604 fix(forms): clear number input
  packages/forms/src/components/Form/Form.test.tsx
  packages/forms/src/hooks/useForm/useForm.ts
Labels: size/M

#606 docs: update documentation for SingleSelect component
  packages/core/src/components/FileInput/FileInput.stories.mdx
  packages/core/src/components/SingleSelect/SingleSelect.stories.mdx
  packages/core/src/components/SingleSelect/types.ts
Labels: size/M

#610 fix(forms): number input accept zero
  packages/forms/src/hooks/useForm/useForm.ts
Labels: size/XS

#620 Feat set modal content overflow
  packages/core/src/components/Modal/Content/Content.styled.tsx
  packages/core/src/components/Modal/Content/types.ts
  packages/core/src/components/Modal/Modal.styled.tsx
  packages/core/src/components/Modal/Modal.tsx
  packages/core/src/components/Modal/Popup/Popup.styled.tsx
  packages/core/src/components/Modal/Popup/__snapshots__/Popup.test.tsx.snap
  packages/core/src/components/Modal/Popup/types.ts
  packages/core/src/components/Modal/__snapshots__/Modal.test.tsx.snap
  packages/core/src/components/Modal/types.ts
Labels: size/M

#621 Feat set modal content overflow
  packages/core/src/components/Modal/Content/Content.tsx
  packages/core/src/components/Modal/Modal.context.ts
  packages/core/src/components/Modal/Modal.tsx
  packages/core/src/components/Modal/types.ts
Labels: size/S

#619 fix(core): expandable and selectable column
  packages/core/src/components/Table/Head/Head.tsx
  packages/core/src/components/Table/docs/Table.stories.mdx
Labels: size/M

#622 fix: single select calling onBlur even on scrollbar click
  packages/core/src/components/SingleSelect/SingleSelect.test.tsx
  packages/core/src/components/SingleSelect/SingleSelect.tsx
  packages/core/src/components/SingleSelect/useKeyboardNavigation.tsx
Labels: bug, size/M

#625 fix: single select inside modal not closing
  packages/core/src/components/Modal/Popup/Popup.tsx
Labels: bug, size/S
