Repository medly/medly-components, pull requests merged in 2022-01, with the labels that each got.

#558 feat: add keyboard navigation for multiselect
  packages/core/src/components/Checkbox/Checkbox.styled.tsx
  packages/core/src/components/Checkbox/Checkbox.tsx
  packages/core/src/components/Checkbox/types.ts
  packages/core/src/components/CheckboxGroup/CheckboxGroup.tsx
  packages/core/src/components/CheckboxGroup/types.ts
  packages/core/src/components/Modal/Modal.stories.mdx
  packages/core/src/components/Modal/Modal.stories.tsx
  packages/core/src/components/Modal/Modal.test.tsx
  packages/core/src/components/Modal/Modal.tsx
  packages/core/src/components/MultiSelect/MultiSelect.test.tsx
  packages/core/src/components/MultiSelect/MultiSelect.tsx
  packages/core/src/components/MultiSelect/Options/Options.tsx
  packages/core/src/components/MultiSelect/Options/types.ts
  packages/core/src/components/Table/Body/Body.tsx
  packages/core/src/components/Table/Body/Row/Row.styled.tsx
  packages/core/src/components/Table/Body/Row/Row.tsx
  packages/core/src/components/Table/Body/Row/__snapshots__/Row.test.tsx.snap
  packages/core/src/components/Table/Body/Row/types.ts
  packages/core/src/components/Table/Table.styled.tsx
  packages/core/src/components/Table/Table.test.tsx
  packages/core/src/components/Table/Table.tsx
  packages/core/src/components/Table/__snapshots__/Table.test.tsx.snap
  packages/core/src/components/Table/constants.ts
  packages/core/src/components/Table/docs/Table.stories.mdx
  packages/core/src/components/Table/types.ts
  packages/utils/src/hooks/useKeyPress/useKeyPress.ts
Labels: enhancement, size/L

#566 refactor(multiselect): keyboard navigation
  packages/core/src/components/CheckboxGroup/CheckboxGroup.tsx
  packages/core/src/components/CheckboxGroup/types.ts
  packages/core/src/components/CheckboxGroup/useKeyboardNavigation.ts
  packages/core/src/components/MultiSelect/MultiSelect.tsx
  packages/core/src/components/MultiSelect/types.ts
  packages/core/src/components/MultiSelect/useKeyboardNavigation.ts
Labels: size/L

#564 feat(js-docs): Add JS docs for hooks
  packages/utils/src/hooks/useAxios/useAxios.ts
  packages/utils/src/hooks/useCombinedRefs/useCombinedRefs.ts
  packages/utils/src/hooks/useMediaQuery/useMediaQuery.ts
  packages/utils/src/hooks/useOuterClickNotifier/useOuterClickNotifier.ts
  packages/utils/src/hooks/useSWRAxios/useSWRAxios.stories.mdx
  packages/utils/src/hooks/useSWRAxios/useSWRAxios.ts
  packages/utils/src/hooks/useStorage/useStorage.ts
  packages/utils/src/hooks/useUpdateEffect/useUpdateEffect.ts
  packages/utils/src/hooks/useWindowSize/useWindowSize.ts
Labels: size/M

#567 feat: add h6 variant in font variants
  packages/theme/src/core/font/types.ts
  packages/theme/src/core/font/variants.ts
Labels: size/XS

#568 Refactor Checkbox group keyboard navigation follow up
  packages/core/src/components/CheckboxGroup/CheckboxGroup.tsx
  packages/core/src/components/CheckboxGroup/types.ts
  packages/core/src/components/CheckboxGroup/useKeyboardNavigation.ts
Labels: size/S

#569 Feat/pmmpp 463
  packages/layout/src/components/Header/Header.stories.mdx
  packages/layout/src/components/Header/NavItem/NavItem.styled.tsx
  packages/layout/src/components/Header/NavItem/__snapshots__/NavItem.test.tsx.snap
Labels: size/S

#572 fix: searchbox options width issue
  packages/core/src/components/DateRangePicker/__snapshots__/DateRangePicker.test.tsx.snap
  packages/core/src/components/SearchBox/SearchBox.stories.mdx
  packages/core/src/components/SearchBox/SearchBox.styled.tsx
  packages/core/src/components/SearchBox/SearchBox.tsx
  packages/core/src/components/SearchBox/__snapshots__/SearchBox.test.tsx.snap
  packages/core/src/components/SearchBox/types.ts
  packages/core/src/components/SingleSelect/Options/Options.styled.tsx
  packages/core/src/components/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap
Labels: size/L

#570 feat: close dateRangePicker if both the inputs are out of focus
  packages/core/src/components/DateRangePicker/DateRangePicker.tsx
Labels: enhancement, size/S

#573 fix: fix singleselect options same key issue
  packages/core/src/components/SearchBox/__snapshots__/SearchBox.test.tsx.snap
  packages/core/src/components/SearchBox/styles/options.tsx
  packages/core/src/components/SingleSelect/Options/Options.tsx
Labels: size/M

#576 feat: call onSearch prop on pressing enter key on SearchBox component
  packages/core/src/components/SearchBox/SearchBox.stories.mdx
  packages/core/src/components/SearchBox/SearchBox.stories.tsx
  packages/core/src/components/SearchBox/SearchBox.tsx
  packages/core/src/components/SearchBox/__snapshots__/SearchBox.test.tsx.snap
  packages/core/src/components/SingleSelect/Options/Option/Option.styled.tsx
  packages/core/src/components/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap
Labels: size/S

#581 fix: fix text component line height issue
  packages/core/src/components/Avatar/__snapshots__/Avatar.test.tsx.snap
  packages/core/src/components/Box/__snapshots__/Box.test.tsx.snap
  packages/core/src/components/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap
  packages/core/src/components/Button/__snapshots__/Button.test.tsx.snap
  packages/core/src/components/Calendar/__snapshots__/Calendar.test.tsx.snap
  packages/core/src/components/Card/__snapshots__/Card.test.tsx.snap
  packages/core/src/components/CardTable/Body/Cell/__snapshots__/Cell.test.tsx.snap
  packages/core/src/components/CardTable/Body/__snapshots__/Body.test.tsx.snap
  packages/core/src/components/CardTable/__snapshots__/CardTable.test.tsx.snap
  packages/core/src/components/CenterAlignedLoader/__snapshots__/CenterAlignedLoader.test.tsx.snap
  packages/core/src/components/Checkbox/__snapshots__/checkbox.test.tsx.snap
  packages/core/src/components/CheckboxGroup/__snapshots__/CheckboxGroup.test.tsx.snap
  packages/core/src/components/Chip/__snapshots__/Chip.test.tsx.snap
  packages/core/src/components/DatePicker/__snapshots__/DatePicker.test.tsx.snap
  packages/core/src/components/DateRangePicker/__snapshots__/DateRangePicker.test.tsx.snap
  packages/core/src/components/FieldWithLabel/__snapshots__/FieldWithLabel.test.tsx.snap
  packages/core/src/components/FileInput/__snapshots__/FileInput.test.tsx.snap
  packages/core/src/components/Input/__snapshots__/Input.test.tsx.snap
  packages/core/src/components/Link/__snapshots__/Link.test.tsx.snap
  packages/core/src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  packages/core/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
  packages/core/src/components/Radio/__snapshots__/radio.test.tsx.snap
  packages/core/src/components/RadioGroup/__snapshots__/RadioGroup.test.tsx.snap
  packages/core/src/components/SearchBox/__snapshots__/SearchBox.test.tsx.snap
  packages/core/src/components/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap
  packages/core/src/components/Stepper/__snapshots__/Stepper.test.tsx.snap
  packages/core/src/components/Table/ActionBar/__snapshots__/ActionBar.test.tsx.snap
  packages/core/src/components/Table/Body/Cell/__snapshots__/Cell.test.tsx.snap
  packages/core/src/components/Table/Foot/__snapshots__/Foot.test.tsx.snap
  packages/core/src/components/Table/GroupCell/__snapshots__/GroupCell.test.tsx.snap
  packages/core/src/components/Table/__snapshots__/Table.test.tsx.snap
  packages/core/src/components/Tabs/Tab/__snapshots__/Tab.test.tsx.snap
  packages/core/src/components/Tabs/TabList/__snapshots__/TabList.test.tsx.snap
  packages/core/src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
  packages/core/src/components/Text/Text.styled.tsx
  packages/core/src/components/Text/__snapshots__/Text.test.tsx.snap
  packages/core/src/components/Toast/__snapshots__/Toast.test.tsx.snap
  packages/core/src/components/ToastContainer/__snapshots__/ToastContainer.test.tsx.snap
  packages/forms/src/components/Actions/__snapshots__/Actions.test.tsx.snap
  packages/forms/src/components/Form/__snapshots__/Form.test.tsx.snap
  packages/layout/src/components/SideNav/NavItem/__snapshots__/NavItem.test.tsx.snap
  packages/layout/src/components/SideNav/ToggleSwitch/__snapshots__/ToggleSwitch.test.tsx.snap
  packages/layout/src/components/SideNav/__snapshots__/SideNav.test.tsx.snap
Labels: size/L
