Repository medly/medly-components, pull requests merged in 2022-05, with the labels that each got.

#654 fix(core): make nested table field resizeable
  packages/core/src/components/Table/helpers.ts
Labels: size/XS

#655 fix(core): add flex-shrink=0 on radio button
  .jest-test-results.json
  packages/core/src/components/Radio/Radio.styled.tsx
  packages/core/src/components/Radio/__snapshots__/radio.test.tsx.snap
  packages/core/src/components/RadioGroup/__snapshots__/RadioGroup.test.tsx.snap
  packages/forms/src/components/Form/__snapshots__/Form.test.tsx.snap
Labels: size/L

#657 fix(core): fix single select issue for async options
  packages/core/src/components/SingleSelect/SingleSelect.tsx
Labels: size/S

#659 feat(core): add prop to expand row by default
  packages/core/src/components/Table/Body/Row/Row.tsx
  packages/core/src/components/Table/Table.test.tsx
  packages/core/src/components/Table/docs/Table.stories.mdx
  packages/core/src/components/Table/types.ts
Labels: size/M

#660 feat(core): adds iconColor prop to Accordion.Header
  packages/core/src/components/Accordion/Header/Header.tsx
  packages/core/src/components/Accordion/types.ts
Labels: size/S

#661 fix: accordion content height issue
  packages/core/src/components/Accordion/Accordion.test.tsx
  packages/core/src/components/Accordion/Accordion.tsx
  packages/core/src/components/Accordion/Content/Content.styled.tsx
  packages/core/src/components/Accordion/types.ts
Labels: size/S
