Repository medly/medly-components, pull requests merged in 2022-06, with the labels that each got.

#666 feat(theme): allow @font-face ascent and descent overrides
  packages/core/src/components/CssBaseline/fonts.tsx
  packages/theme/src/core/font/types.ts
Labels: size/XS

#670 feat: add controlled cursor and onRowNavigated for Table
  packages/core/src/components/Table/Body/Body.tsx
  packages/core/src/components/Table/Body/Row/Row.tsx
  packages/core/src/components/Table/Body/Row/types.ts
  packages/core/src/components/Table/Body/types.ts
  packages/core/src/components/Table/Table.test.tsx
  packages/core/src/components/Table/Table.tsx
  packages/core/src/components/Table/docs/Table.stories.mdx
  packages/core/src/components/Table/types.ts
Labels: enhancement, size/L

#671 fix: escape key closes all modal instead of top modal
  packages/core/src/components/Modal/Modal.stories.mdx
  packages/core/src/components/Modal/Modal.test.tsx
  packages/core/src/components/Modal/Modal.tsx
  packages/core/src/components/Modal/ModalManager/ModalManager.test.tsx
  packages/core/src/components/Modal/ModalManager/ModalManager.ts
  packages/core/src/components/Modal/ModalManager/index.ts
  packages/core/src/components/Modal/ModalManager/types.ts
  packages/core/src/components/Modal/types.ts
Labels: bug, enhancement, size/L

#673 feat: add support for keybinding to select row in Table component
  packages/core/src/components/Table/Body/Cell/RowActionsCell/RowActionsCell.tsx
  packages/core/src/components/Table/Body/Row/Row.tsx
  packages/core/src/components/Table/Table.test.tsx
  packages/core/src/components/Table/constants.ts
  packages/core/src/components/Table/docs/Table.stories.mdx
  packages/core/src/components/Table/types.ts
Labels: enhancement, size/M

#674 fix: Table component noResultRow prop vertical scroll issue
  packages/core/src/components/Table/Body/Body.test.tsx
  packages/core/src/components/Table/Body/Body.tsx
  packages/core/src/components/Table/Body/__snapshots__/Body.test.tsx.snap
  packages/core/src/components/Table/Table.test.tsx
  packages/core/src/components/Table/docs/Table.stories.mdx
Labels: size/XL

#675 fix(core): file input placeholder value
  packages/forms/src/components/Fields/Fields.components.tsx
Labels: bug, size/XS

#678 feat: add isLoading and custom loader support in search box
  packages/core/src/components/SearchBox/SearchBox.stories.mdx
  packages/core/src/components/SearchBox/SearchBox.test.tsx
  packages/core/src/components/SearchBox/SearchBox.tsx
  packages/core/src/components/SearchBox/types.ts
Labels: enhancement, size/M

#667 feat: add icon support in toggle button
  packages/core/src/components/Toggle/Toggle.stories.mdx
  packages/core/src/components/Toggle/Toggle.styled.tsx
  packages/core/src/components/Toggle/Toggle.test.tsx
  packages/core/src/components/Toggle/Toggle.tsx
  packages/core/src/components/Toggle/__snapshots__/Toggle.test.tsx.snap
  packages/core/src/components/Toggle/types.ts
  packages/theme/src/core/toggle/index.ts
  packages/theme/src/core/toggle/types.ts
Labels: enhancement, size/L

#642 Intro
  docs/Introduction.stories.mdx
Labels: size/M

#680 chore(packages): add command to remove symlink for packages
  package.json
Labels: size/XS

#679 PSB | fix(core): remove clearing of value using ref
  packages/core/src/components/FileInput/FileInput.tsx
Labels: size/XS

#681 fix(core): fix table security issue
  packages/core/src/components/Table/Body/Cell/Cell.tsx
  packages/core/src/components/Table/Table.test.tsx
  packages/core/src/components/Table/__snapshots__/Table.test.tsx.snap
Labels: size/XL

#676 feat(core): update modal styling and behavior
  packages/core/src/components/Modal/Actions/Actions.styled.tsx
  packages/core/src/components/Modal/Content/Content.styled.tsx
  packages/core/src/components/Modal/Header/Header.styled.tsx
  packages/core/src/components/Modal/Header/Header.tsx
  packages/core/src/components/Modal/Header/__snapshots__/Header.test.tsx.snap
  packages/core/src/components/Modal/Modal.styled.tsx
  packages/core/src/components/Modal/Modal.tsx
  packages/core/src/components/Modal/Popup/Popup.styled.tsx
  packages/core/src/components/Modal/Popup/__snapshots__/Popup.test.tsx.snap
  packages/core/src/components/Modal/__snapshots__/Modal.test.tsx.snap
  packages/core/src/components/Modal/useScrollState.ts
  packages/utils/src/style/media/media.ts
Labels: size/L
