Repository medly/medly-components, pull requests merged in 2022-04, with the labels that each got.

#607 docs: update stepper component docs
  packages/core/src/components/Stepper/Stepper.stories.mdx
  packages/core/src/components/Stepper/types.ts
  packages/core/src/components/Text/Text.stories.mdx
  packages/core/src/components/Text/types.ts
Labels: size/M

#612 docs: update docs of toggle component
  packages/core/src/components/Toggle/Toggle.stories.mdx
  packages/core/src/components/Toggle/types.ts
Labels: size/S

#624 docs: update docs of tabs component
  packages/core/src/components/Tabs/Tab/types.ts
  packages/core/src/components/Tabs/Tabs.stories.mdx
  packages/core/src/components/Tabs/types.ts
Labels: size/M

#608 docs: update docs of textfield component
  packages/core/src/components/TextField/TextField.stories.mdx
  packages/core/src/components/TextField/types.ts
Labels: size/M

#614 docs: update docs of hidden component
  packages/core/src/components/Hidden/Hidden.stories.mdx
  packages/core/src/components/Hidden/types.ts
Labels: size/S

#616 docs: update docs of logo component
  packages/core/src/components/Logo/Logo.stories.mdx
Labels: size/S

#617 docs: update docs of multiselect component
  packages/core/src/components/MultiSelect/MultiSelect.stories.mdx
  packages/core/src/components/MultiSelect/types.ts
Labels: size/S

#623 docs: update docs of table component
  packages/core/src/components/Table/docs/Table.stories.mdx
  packages/core/src/components/Table/types.ts
Labels: size/M

#630 feat: add custom label component to checkbox
  packages/core/src/components/Checkbox/Checkbox.stories.mdx
  packages/core/src/components/Checkbox/Checkbox.stories.tsx
  packages/core/src/components/Checkbox/Checkbox.tsx
  packages/core/src/components/Checkbox/checkbox.test.tsx
  packages/core/src/components/Checkbox/types.ts
Labels: size/M

#632 feat(layout): add custom expand & collapse text in sidenav
  packages/layout/src/components/SideNav/SideNav.stories.mdx
  packages/layout/src/components/SideNav/SideNav.tsx
  packages/layout/src/components/SideNav/ToggleSwitch/ToggleSwitch.test.tsx
  packages/layout/src/components/SideNav/ToggleSwitch/ToggleSwitch.tsx
  packages/layout/src/components/SideNav/ToggleSwitch/__snapshots__/ToggleSwitch.test.tsx.snap
  packages/layout/src/components/SideNav/ToggleSwitch/types.ts
  packages/layout/src/components/SideNav/types.ts
Labels: size/M

#633 fix(core): persists X in SearchBox after pressing enter
  packages/core/src/components/SearchBox/SearchBox.test.tsx
  packages/core/src/components/SearchBox/SearchBox.tsx
Labels: size/S

#634 feat: add custom message support in centerAlignLoader
  packages/core/src/components/CenterAlignedLoader/CenterAlignedLoader.stories.mdx
  packages/core/src/components/CenterAlignedLoader/CenterAlignedLoader.styled.tsx
  packages/core/src/components/CenterAlignedLoader/CenterAlignedLoader.test.tsx
  packages/core/src/components/CenterAlignedLoader/CenterAlignedLoader.tsx
  packages/core/src/components/CenterAlignedLoader/__snapshots__/CenterAlignedLoader.test.tsx.snap
  packages/core/src/components/CenterAlignedLoader/types.ts
Labels: size/L

#635 fix: add key prop for pagination popup
  packages/core/src/components/Pagination/Pagination.tsx
Labels: bug, size/XS

#618 docs: update docs of searchbox component
  packages/core/src/components/SearchBox/SearchBox.stories.mdx
  packages/core/src/components/SearchBox/types.ts
Labels: size/S

#613 docs: update docs of daterangepicker component
  packages/core/src/components/DateRangePicker/DateRangePicker.stories.mdx
  packages/core/src/components/DateRangePicker/types.ts
Labels: size/M

#611 docs: update content of toast container component
  packages/core/src/components/ToastContainer/ToastContainer.stories.mdx
Labels: size/S

#649 feat: add masking on copy paste in textfield component
  packages/core/src/components/TextField/TextField.stories.mdx
  packages/core/src/components/TextField/getMaskedValue.test.ts
  packages/core/src/components/TextField/getMaskedValue.ts
Labels: size/M

#652 docs: move deprecated components to different folder in storybook
  packages/core/src/components/CardTable/docs/CardTable.stories.mdx
  packages/core/src/components/Input/Input.stories.mdx
Labels: size/XS

#647 AM|content changes-loaders
  packages/loaders/src/Loaders.stories.mdx
Labels: size/S

#648 AM|content changes-icons
  packages/icons/src/Icons.stories.mdx
Labels: size/S

#645 Layoutheader
  packages/layout/src/components/Header/Header.stories.mdx
Labels: size/S

#643 Typography
  docs/Typography/Typography.stories.mdx
Labels: size/S

#640 AM|content changes- components
  packages/utils/src/components/InjectClassName/InjectClassName.stories.mdx
Labels: size/XS

#639 AM|content changes-types
  packages/utils/src/types/GetComponentProps/GetComponentProps.stories.mdx
  packages/utils/src/types/HTMLProps/HTMLProps.stories.mdx
  packages/utils/src/types/WithStyle/WithStyle.stories.mdx
Labels: size/S
