Repository medly/medly-components, pull requests merged in 2022-08, with the labels that each got.

#692 feat(core): updated core modal border radius and padding
  packages/core/src/components/Modal/Header/Header.styled.tsx
  packages/core/src/components/Modal/Header/__snapshots__/Header.test.tsx.snap
  packages/core/src/components/Modal/Modal.tsx
  packages/core/src/components/Modal/Popup/Popup.styled.tsx
  packages/core/src/components/Modal/Popup/__snapshots__/Popup.test.tsx.snap
  packages/core/src/components/Modal/__snapshots__/Modal.test.tsx.snap
Labels: size/M

#691 feat(core): add showAllOptionsOnNoResult and noResultComponent in multi select
  packages/core/src/components/MultiSelect/MultiSelect.stories.mdx
  packages/core/src/components/MultiSelect/MultiSelect.test.tsx
  packages/core/src/components/MultiSelect/MultiSelect.tsx
  packages/core/src/components/MultiSelect/Options/Options.tsx
  packages/core/src/components/MultiSelect/Options/types.ts
  packages/core/src/components/MultiSelect/types.ts
Labels: bug, enhancement, size/M

#693 fix(core): fix close icon bug, when initial value is provided.
  packages/core/src/components/SearchBox/SearchBox.test.tsx
  packages/core/src/components/SearchBox/SearchBox.tsx
Labels: size/XS

#695 fix: Resolve single select field validation issue
  packages/core/src/components/SingleSelect/SingleSelect.tsx
Labels: size/XS

#696 revert: sidenav and drawer height issue on mobile devices
  packages/core/src/components/Drawer/Drawer.styled.tsx
  packages/core/src/components/Drawer/__snapshots__/Drawer.test.tsx.snap
  packages/layout/src/components/Header/Nav/Nav.styled.tsx
  packages/layout/src/components/SideNav/__snapshots__/SideNav.test.tsx.snap
  packages/layout/src/components/SidePanel/SidePanel.styled.tsx
  packages/layout/src/components/SidePanel/__snapshots__/SidePanel.test.tsx.snap
Labels: bug, size/S

#641 AM|content changes-markdown
  packages/markdown/src/components/MarkdownContent/MarkdownContent.stories.mdx
Labels: size/M

#637 AM|content change-style
  packages/utils/src/style/breakpoints/breakpoints.stories.mdx
  packages/utils/src/style/centerAligned/centerAligned.stories.mdx
  packages/utils/src/style/getFontStyle/getFontStyle.stories.mdx
  packages/utils/src/style/media/media.stories.mdx
Labels: size/M

#638 AM|content changes-helpers
  packages/utils/src/helpers/cookieStorage/cookieStorage.stories.mdx
  packages/utils/src/helpers/debounce/debounce.stories.mdx
  packages/utils/src/helpers/localStorage/localStorage.stories.mdx
  packages/utils/src/helpers/sessionStorage/sessionStorage.stories.mdx
  packages/utils/src/helpers/updateNestedValue/updateNestedValue.stories.mdx
Labels: size/M

#636 AM|contetnt changes-hooks
  packages/utils/src/hooks/useAxios/useAxios.stories.mdx
  packages/utils/src/hooks/useCombinedRefs/useCombinedRefs.stories.mdx
  packages/utils/src/hooks/useKeyPress/useKeyPress.stories.mdx
  packages/utils/src/hooks/useMediaQuery/useMediaQuery.stories.mdx
  packages/utils/src/hooks/useOuterClickNotifier/useOuterClickNotifier.stories.mdx
  packages/utils/src/hooks/useSWRAxios/useSWRAxios.stories.mdx
  packages/utils/src/hooks/useUpdateEffect/useUpdateEffect.stories.mdx
  packages/utils/src/hooks/useWindowSize/useWindowSize.stories.mdx
Labels: size/M
