Repository medly/medly-components, pull requests merged in 2023-07, with the labels that each got.

#731 fix(core): searchBox: clear/close icon not hiding when we manually clear the state value
  packages/core/src/components/SearchBox/SearchBox.tsx
  packages/core/src/components/SearchBox/__snapshots__/SearchBox.test.tsx.snap
Labels: size/S

#734 refactor: remove chromatic and add separate storybook workflow
  .github/workflows/chromatic.yml
  .github/workflows/storybook.yml
  .storybook/static/CNAME
Labels: size/M

#733 fix(core): singleSelect - search filter not working well due to duplicate key issue.
  packages/core/src/components/SingleSelect/Options/Options.tsx
Labels: size/XS

#714 chore: use nrwl/nx-set-shas in github actions
  .github/workflows/lint-test-build.yml
  .github/workflows/release.yml
  .github/workflows/storybook.yml
  package.json
Labels: size/S
